### ISSUE TITLE
JSON omitempty is not always correct

### ISSUE THREAD

**Issue by croachrose** [google/google-api-go-client#101]
I am writing a statistics service that uploads custom metrics to cloudmonitoring. I am using the generated go binds to upload stats.

In the generated bindings for the Point struct, there are fields (Int64Value and DoubleValue) that are allowed for custom metrics. However, I am unable to upload a 0 for either field as a valid metric because the field is omitted and the cloud monitoring service complains that the field is missing.

The first option that comes to mind is making the field a pointer. The other option would be to somehow indicate that the field should be included but that seems to be more difficult.

**Comment by gmlewis** [comment]
Please see the ongoing discussion in issue #54 and move this discussion over there.
@mcgreevy has added the capability to whitelist individual fields here to make them pointers:
https://github.com/google/google-api-go-client/commit/4af91da60108e4a6d2547bb4adce3f611c4d1f20
It may be a simple matter to whitelist those individual fields.
Could you please try that out and let me know if it fixes the issue?
You could then either see the CONTRIBUTING.md doc and put together a Gerrit code review or you could let me know that it worked for you and I can put together one.
Either way, I'll close this issue and let's move this discussion over to #54.
