### ISSUE TITLE
BigQuery API doesn't have latest fields

### ISSUE THREAD

**Issue by dolzenko** [google/google-api-go-client#102]
E.g. `statistics.query.totalBytesBilled/billingTier` from  https://cloud.google.com/bigquery/docs/reference/v2/jobs

**Comment by gmlewis** [comment]
It appears that this new API version has not been published yet:
https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest
I'll contact the BigQuery team to find out why.

**Comment by gmlewis** [comment]
ETA for BigQuery API update: approximately two weeks.

**Comment by gmlewis** [comment]
Update from BigQuery team - this may be pushed out until November 1, 2015.

**Comment by dsymonds** [comment]
I think bigquery is up to date now. `billingTier`, for instance, showed up in ebc77990.
