### ISSUE TITLE
how to specify object as response in storage ObjectsService.Get

### ISSUE THREAD

**Issue by lastid** [google/google-api-go-client#103]
https://godoc.org/google.golang.org/api/storage/v1#ObjectsService.Get
> Get: Retrieves an object or its metadata.

How can I retrieve the object not its metadata?

**Comment by drichardson** [comment]
Use the https://godoc.org/google.golang.org/api/storage/v1#ObjectsInsertCall.Media call.

**Comment by drichardson** [comment]
Sorry, should have been the https://godoc.org/google.golang.org/api/storage/v1#ObjectsGetCall.Download call.

**Comment by lastid** [comment]
It works. Thank you.
