### ISSUE TITLE
google-api-go-client won't build in Go 1.5 because it imports a internal package

### ISSUE THREAD

**Issue by joseferminj** [google/google-api-go-client#106]
$ go get -u github.com/google/google-api-go-client/pubsub/v1beta2
package github.com/google/google-api-go-client/pubsub/v1beta2
	imports google.golang.org/api/internal: use of internal package not allowed

The internal package 'google.golang.org/api/internal' import was added by d604dad6fa7f098a8ac36a19598c161acf70c5c3

**Comment by bradfitz** [comment]
You're cloning it from the wrong location. You should do:

```
$ go get -u google.golang.org/api/pubsub/v1beta2
```

But if we added import declarations to the top of the files (https://golang.org/s/go14customimport) then the go tool would've told you this automatically instead of confusing you.

/cc @gmlewis @mcgreevy

**Comment by joseferminj** [comment]
It worked. My fault for not using the correct import.
Thanks.
