### ISSUE TITLE
If-None-Match on non-GET APIs?

### ISSUE THREAD

**Issue by bradfitz** [google/google-api-go-client#107]
Do any Google APIs support If-None-Match on non-GET method calls?

e.g. should we include methods like:

``` go
func (c *ArchiveInsertCall) IfNoneMatch(entityTag string) *ArchiveInsertCall {
```

?

I think we won't for now, but add them if we find a supporting example, even if it's just a single API.

The spec (http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) section 14.26 says it's also meant for PUT, etc. But does Google do that anywhere?

Related to issue #86 (ETag, etc)
/cc @gmlewis @mcgreevy @ImJasonH

**Comment by mcgreevy** [comment]
The case that immediately came to mind was cloud storage, but they have custom in-band mechanisms for this kind of thing https://cloud.google.com/storage/docs/json_api/v1/objects/update#ifGenerationNotMatch

**Comment by jba** [comment]
These clients are in maintenance mode. We don't plan to address this issue.

@pongad for the next generation of clients.
