### ISSUE TITLE
Project parameter missing on storage bucket insert

### ISSUE THREAD

**Issue by phinze** [google/google-api-go-client#110]
After @gmlewis's fix for #105 landed in 69e492629e49bc7ff3c791ac7630836813268b45, I've started to see failures with the following message:

```
Error 400: Required parameter: project, required
```

This is occurring at least on storage bucket insert. I have yet to test elsewhere. Will follow up as I learn more, but wanted to get a report made first in case it's an easy fix.

**Comment by gmlewis** [comment]
Sorry about the breakage.
@mcgreevy - how about if I revert until I can figure out the breakage and add unit tests?

**Comment by mcgreevy** [comment]
@gmlewis yes, please do.

**Comment by gmlewis** [comment]
https://code-review.googlesource.com/#/c/3592/

**Comment by mcgreevy** [comment]
reviewed and submitted.

**Comment by gmlewis** [comment]
Thanks, Michael!  I'll investigate tomorrow.

**Comment by gmlewis** [comment]
I found the problem in the diffs... note how the "projectid" parameter got mapper to the name "project" before the change, but after the change it got mapped to "projectid", causing the breakage.  I have a bunch of meetings this morning but will hopefully get back to this later today:

@@ -2271,23 +2226,9 @@ func (c *BucketsInsertCall) doRequest(alt string) (*http.Response, error) {
                return nil, err
        }
        ctype := "application/json"
-       params := make(url.Values)
-       params.Set("alt", alt)
-       params.Set("project", fmt.Sprintf("%v", c.projectid))
-       if v, ok := c.opt_["predefinedAcl"]; ok {
-               params.Set("predefinedAcl", fmt.Sprintf("%v", v))
-       }
-       if v, ok := c.opt_["predefinedDefaultObjectAcl"]; ok {
-               params.Set("predefinedDefaultObjectAcl", fmt.Sprintf("%v", v))
-       }
-       if v, ok := c.opt_["projection"]; ok {
-               params.Set("projection", fmt.Sprintf("%v", v))
-       }
-       if v, ok := c.opt_["fields"]; ok {
-               params.Set("fields", fmt.Sprintf("%v", v))
-       }
+       c.urlParams_.Set("alt", alt)
        urls := googleapi.ResolveRelative(c.s.BasePath, "b")
-       urls += "?" + params.Encode()
+       urls += "?" + c.urlParams_.Encode()
        req, _ := http.NewRequest("POST", urls, body)
        googleapi.SetOpaque(req.URL)
        req.Header.Set("Content-Type", ctype)
@@ -2420,23 +2361,23 @@ func (c *BucketsInsertCall) Do() (*Bucket, error) {
 // method id "storage.buckets.list":
 
 type BucketsListCall struct {
-       s         *Service
-       projectid string
-       opt_      map[string]interface{}
-       ctx_      context.Context
+       s            *Service
+       urlParams_   internal.URLParams
+       ifNoneMatch_ string
+       ctx_         context.Context
 }
 
 // List: Retrieves a list of buckets for a given project.
 func (r *BucketsService) List(projectid string) *BucketsListCall {
-       c := &BucketsListCall{s: r.s, opt_: make(map[string]interface{})}
-       c.projectid = projectid
+       c := &BucketsListCall{s: r.s, urlParams_: make(internal.URLParams)}
+       c.urlParams_.Set("projectid", projectid)
        return c
 }

**Comment by gmlewis** [comment]
Michael and I have a CL that we believe fixes this issue
(located here: https://code-review.googlesource.com/#/c/3610 )
but would like to get integration tests incorporated into the project before submitting this so that we don't have another breakage of a major API.
Feel free to patch in the CL and try it out if you would like repeated parameters.
