### ISSUE TITLE
google-api-go-generator is not usable for external APIs.

### ISSUE THREAD

**Issue by danjacques** [google/google-api-go-client#112]
In order to use Google [Cloud Endpoints](https://cloud.google.com/endpoints/) from Go, some form of interface to the endpoint must be implemented. `google-api-go-generator` is almost completely up to the task; however, it is missing a few features to make external usage smooth and optimal:
* Generated packages reference the [internal](https://github.com/google/google-api-go-client/tree/master/internal) package, which makes externally generated APIs **unusable** in Go 1.5+.
* The user cannot override the base URL used in service instantiation (`myservice.New("")`). This is useful, but not necessary, when generating from a local `dev_appserver.py` instance, which exposes the root URL `localhost:8080`.
* The tool cannot prepend a license header to the generated stubs. Some tools, such as [pre-commit-go](https://github.com/maruel/pre-commit-go), enforce license checks, and this is useful to facilitate this conformity.

**Comment by zboralski** [comment]
We've been using the generator with our own endpoints... a bit of a hack as it involves copying the googleapi folder in your own client repo. I'll post a script if you're interested.

**Comment by danjacques** [comment]
Yeah I'm doing something similar at the moment - less copying and more forking. I'm hoping to avoid both :)

I have this CL up as a first shot at accomplishing this: https://code-review.googlesource.com/3706

**Comment by zboralski** [comment]
@mcgreevy awesome! Thanks

**Comment by zboralski** [comment]
@mcgreevy you missed a spot :) uritemplates are missing https://github.com/google/google-api-go-client/issues/116

**Comment by mcgreevy** [comment]
Replied on #116.
