### ISSUE TITLE
Move elements from googleapi to internal package where possible.

### ISSUE THREAD

**Issue by mcgreevy** [google/google-api-go-client#113]
googleapi has become the de facto location for helper functions etc. which are intended to be used by developers (e.g. IfNoneModified).  However, there also remain a bunch of functions which are implementation details (e.g. CombineFields).  These implementation details should be moved into the internal package.

**Comment by jba** [comment]
These clients are in maintenance mode. We don't plan to address this issue.

@pongad for the next generation of clients.
