### ISSUE TITLE
calendar.go ( undefined registerDemo )

### ISSUE THREAD

**Issue by jcmartins** [google/google-api-go-client#115]
In calendar.go line 17 registerDemo undefined

func init() {
	registerDemo("calendar", calendar.CalendarScope, calendarMain)
}

**Comment by bradfitz** [comment]
registerDemo is part of the demo app. Look at the rest of the code and its package main, etc.

**Comment by jcmartins** [comment]
I only desire use the calendar api.
In the main.go I have error undefined logtransport line 72
Transport: &logTransport{http.DefaultTransport},

tks
