### ISSUE TITLE
googleapi.go is referencing google.golang.org/api/googleapi/internal/uritemplates

### ISSUE THREAD

**Issue by zboralski** [google/google-api-go-client#116]
2015/12/14 17:51:36 Can't find package "google.golang.org/api/googleapi/internal/uritemplates" in $GOPATH: cannot find package "google.golang.org/api/googleapi/internal/uritemplates" in any of:
	/Users/az/go_appengine/goroot/src/google.golang.org/api/googleapi/internal/uritemplates (from $GOROOT)
	/Users/az/go/src/google.golang.org/api/googleapi/internal/uritemplates (from $GOPATH)

**Comment by mcgreevy** [comment]
@zboralski it seems reasonable to me for google.golang.org/api/googleapi to import google.golang.org/api/googleapi/internal/uritemplates.  This shouldn't cause any issues for code that imports googleapi.  Does google.golang.org/api/googleapi/internal/uritemplates actually exist on your machine?  Perhaps you need to
go get -u
?

**Comment by zboralski** [comment]
For some reason I thought it was missing from https://github.com/google/google-api-go-client/tree/master/googleapi
