### ISSUE TITLE
google-api-go-generator doesn't correctly deal with []byte fields

### ISSUE THREAD

**Issue by riannucci** [google/google-api-go-client#117]
Currently if you define an endpoint (e.g. with [https://github.com/GoogleCloudPlatform/go-endpoints]) as

``` go
type RequestType struct {
  Field []byte
}
```

which would then show up something like:

``` json
"RequestType": {
  "id": "RequestType",
  "type": "object",
  "properties": {
    "Field": {
      "type": "string",
      "format": "byte"
    }
  }
}
```

Currently, this will get translated back into a generated struct like:

``` go
type RequestType struct {
  Field string
}
```

But it should really look like the original :)

**Comment by riannucci** [comment]
Looks like inserting

```go
		case "byte":
			gotype = "[]byte"
```

At https://github.com/google/google-api-go-client/blob/master/google-api-go-generator/gen.go#L2240 is enough. I'll make a real gerrit CL for this tomorrow, unless someone beat me to it.

**Comment by jba** [comment]
Closed due to lack of activity.
