### ISSUE TITLE
prediction/v1.6 Output.OutputValue with wrong type

### ISSUE THREAD

**Issue by sztelzer** [google/google-api-go-client#120]
Prediction v1.6 API returns OutputValue as string, but Output.OutputValue is float64.
This brakes on binding the response JSON on Output struct type.

On https://github.com/google/google-api-go-client/blob/master/prediction/v1.6/prediction-api.json
...
"outputValue": {
     "type": "number",
     "description": "The estimated regression value (Regression models only).",
     "format": "double"
    },
...

Example of regression Prediction API response with outputValue as string:
{
 "kind": "prediction#output",
 "id": "*****",
 "selfLink": "https://www.googleapis.com/prediction/v1.6/projects/*****/trainedmodels/*****/predict",
 "outputValue": "3.271555"
}

error: json: cannot unmarshal string into Go value of type float64

Setting Output.OutputValue to go type string resolves it.

**Comment by mcgreevy** [comment]
Looks like this is due to a change in the type of outputValue in the discovery doc, which was itself a bug fix.

I've regenerated the APIs to pick this change up: https://code-review.googlesource.com/#/c/4004/
