### ISSUE TITLE
Reduce/Eliminate manual steps in OAuth flow

### ISSUE THREAD

**Issue by vsubramani** [google/google-api-go-client#122]
When using the go libraries for obtaining OAuth credentials to use with APIs hosted on GCP, these manual steps are involved:
1. Copy Auth url to browser
2. Accept on the consent screen
3. Copy the auth code into the go application

See example https://developers.google.com/google-apps/calendar/quickstart/go

Google API client libraries for other languages host an http listener thereby avoiding the need for  manual steps 1 and 3. Please consider doing similar for the go client libraries.

**Comment by broady** [comment]
This issue is unrelated to this library, and also just not true.

Here is an example on how to do it: https://github.com/nf/streak/blob/master/oauth.go
