### ISSUE TITLE
ResumableMedia upload behaviour changed in latest commits

### ISSUE THREAD

**Issue by clementdenis** [google/google-api-go-client#126]
Since b55544c941dfadb60c112dbeb8e1354f1c2c34bf, ResumableMedia uploads do not reset the position the ReaderAt parameter as it used to. It results in uploading 0 byte files with existing code if the Reader was already read, which creates corrupted files.

**Comment by mcgreevy** [comment]
Thanks for reporting, Clément.  I'll take a look.
