### ISSUE TITLE
Update the container/v1 generated libraries

### ISSUE THREAD

**Issue by roberthbailey** [google/google-api-go-client#127]
For instance, the NodeConfig type in the generated libraries doesn't contain the metadata field (see https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters#NodeConfig).

**Comment by dsymonds** [comment]
The discovery doc for container:v1 is https://www.googleapis.com/discovery/v1/apis/container/v1/rest and that doesn't mention anything about a metadata field for NodeConfig. You'll need to chase that up with whoever owns that API.

**Comment by roberthbailey** [comment]
Thanks; I'll look into how I can get the discovery doc updated to match the public documentation.

**Comment by evandbrown** [comment]
Also, the `Cluster` type is missing the `subnetworks` field.

**Comment by evandbrown** [comment]
@roberthbailey got https://www.googleapis.com/discovery/v1/apis/container/v1/rest updated to include a number of new features. Would love to see a new version of the client to surface these. Thanks, everyone!

**Comment by mcgreevy** [comment]
@broady this looks fixed.  Is there anything else to be done here?
