### ISSUE TITLE
How to create a custom subnetted Network with Golang client?

### ISSUE THREAD

**Issue by sl1pm4t** [google/google-api-go-client#129]
I'm trying to create a new Network using custom subnetting rather than auto subnetting or legacy mode.
The following always results in a legacy mode network with the default subnet range of 10.240.0.0/16:
```go
network := &compute.Network{
  Name:                  "custom-network",
  AutoCreateSubnetworks: false,
  Description:           "custom-network",
}
```

What in the request triggers the Google Cloud API server to create a legacy network vs a new Subnetted type network? 

If I set `AutoCreateSubnetworks = true` then Google creates a new style subnetted network, but the subnets are auto generated, which is not what I want.

**Comment by billf** [comment]
try adding to your composite:

`
  ForceSendFields: []string{"AutoCreateSubnetworks"},
`

to send `AutoCreateSubnetworks` even though the value is the default of false.
this distinguishes between unset (legacy) and explicitly set false (custom).

**Comment by sl1pm4t** [comment]
Thanks, that did the trick.
