### ISSUE TITLE
make google dfp api for go clients?

### ISSUE THREAD

**Issue by c0b** [google/google-api-go-client#135]
so far have java .net php python and ruby; but would really like to write dfp client app in **Go**

https://developers.google.com/doubleclick-publishers/docs/clients

**Comment by cajund** [comment]
A blog post that points us in the right direction to get set up would be helpful. Once connected, we can use the other libraries as reference.

Why is this excluded, anyway? Low volume?

**Comment by gmlewis** [comment]
I suggest that you contact that team directly using the "Send Feedback" link on the URL you provided and ask them for a Go client library. This repo can only generate APIs for publicly accessible API descriptions from the API discovery site: https://www.googleapis.com/discovery/v1/apis/
and their API doesn't appear to be there.
Closing issue.
