### ISSUE TITLE
Create new Project with CloudResourceManager API

### ISSUE THREAD

**Issue by sethvargo** [google/google-api-go-client#138]
Hi there,

I was taking a look at https://github.com/google/google-api-go-client/blob/master/cloudresourcemanager/v1/cloudresourcemanager-gen.go, and it doesn't look like there's currently a function to create projects via the API. 

It looks like [it's present in the Ruby lib](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/resource_manager.rb#L159-L172), but how can I create a project using the Go SDK?

I'm happy to contribute, but it looks like a lot of this is codegen, so I'm not sure where to go.

**Comment by mcgreevy** [comment]
Try the v1beta1 version, which contains this functionality:
https://github.com/google/google-api-go-client/blob/master/cloudresourcemanager/v1beta1/cloudresourcemanager-gen.go

**Comment by sethvargo** [comment]
Perfect thanks!
