### ISSUE TITLE
Cannot parse response when the API returns "NaN" fields

### ISSUE THREAD

**Issue by kyoh86** [google/google-api-go-client#139]
At `google.golang.org/api/webmasters/v3.SearchanalyticsService.Query`, if the API responded "NaN" fields, that fails.

An error for example:

```
json: cannot unmarshal string into Go value of type float64
```

A response for example:

```
cache-control:  no-cache, no-store, max-age=0, must-revalidate
content-encoding:  gzip
content-length:  128
content-type:  application/json; charset=UTF-8
date:  Fri, 08 Apr 2016 13:46:38 GMT
expires:  Fri, 01 Jan 1990 00:00:00 GMT
pragma:  no-cache
server:  GSE
vary:  Origin, X-Origin
{
 "rows": [
  {
   "clicks": 0,
   "impressions": 0,
   "ctr": "NaN",
   "position": "NaN"
  }
 ],
 "responseAggregationType": "byProperty"
}
```

That seems to be done right, but it's unacceptable.
Should I presume that error always means 0-impressions?

**Comment by ncw** [comment]
I just noticed this too with a google picture viewed throught the Google Drive API.

Note the `"altitude": "NaN"` which causes `json: cannot unmarshal string into Go value of type float64` to be returned from `svc.Files.List().Q(query).MaxResults(1000)` using the drive v2 api.

I've removed most of the JSON and adjusted the latitude and longitude to protect the privacy of the individual who sent me this example.

```
{
 "kind": "drive#fileList",
 "items": [
  {
   "kind": "drive#file",
   [snip]
   "imageMediaMetadata": {
    "width": 1200,
    "height": 1600,
    "rotation": 0,
    "location": {
     "latitude": 10.0,
     "longitude": -10.0,
     "altitude": "NaN"
    },
    "date": "2009:09:06 20:55:35",
    "cameraMake": "Apple",
    "cameraModel": "iPhone",
    "aperture": 2.8,
    "colorSpace": "sRGB"
   },
   "spaces": [
    "photos",
    "drive"
   ]
  }
 ]
}
```

**Comment by jba** [comment]
Does the spec for our APIs say that NaN is a valid value? In other words, is the client broken, or the server?
@bradfitz @zombiezen

**Comment by ncw** [comment]
@jba From my reading, strictly speaking, JSON can't actually encode a NaN so I'd say the problem is the server.

However it is a common extension to add NaN to JSON (eg [allow_nan in python](https://docs.python.org/2/library/json.html#basic-usage) - but that would produce `altitude: NaN` instead of `altitude: "NaN"`.

IMHO the server should just leave out float attributes which can't be encoded into JSON such as NaN, Infinity and -Infinity rather than attempt to use a non standard encoding.

**Comment by zombiezen** [comment]
The server shouldn't produce these (it's not valid JSON).  The fix for the client-side would be too invasive.

**Comment by jba** [comment]
We do encode large integers as strings, though, don't we? Maybe this is of the same ilk. I'd love to see some sort of spec.

**Comment by jba** [comment]
@zombiezen to put it another way, that document _is_ valid JSON. It just encodes something you can't express in JSON as best it can.

**Comment by zombiezen** [comment]
Fair enough. So we could modify generated client code to use a type that implements `json.Marshaler` and `json.Unmarshaler` that detects this string/float oddity, but it would break our current API surface.  I somewhat doubt that we can extend the `encoding/json` to support this edge case, whereas the int64 trick comes up very often.

**Comment by bradfitz** [comment]
JSON and JavaScript are different. JSON permits long integers, longer than JavaScript doubles. Thus, quoting long integers in strings makes sense. It's safe for JavaScript, and still legal JSON.

A bare `NaN` on the other hand is simply not legal JSON.

**Comment by jba** [comment]
This is not a bare NaN, it is the string "NaN" in a float64 field.

**Comment by jba** [comment]
I confirmed with Hong that "NaN" can be sent for a float field.

We could provide custom Decode methods on all the response types. I don't think that would break anything.  I'm not sure how hard it would be.
