### ISSUE TITLE
APIs don't handle unions well

### ISSUE THREAD

**Issue by stephenmw** [google/google-api-go-client#140]
example: lets say I am using google.golang.org/api/cloudbuild/v1

I then do op, err = cb.Operations.Get(opName).Do(). In order to get the id of the operation, I need to do:

id := op.Metadata.(map[string]interface{})["build"].(map[string]interface{})["id"].(string)

Instead I would expect Metadata to be an interface{} containing a BuildOperationMetadata

**Comment by stephenmw** [comment]
The issue here is that an Operation takes/returns "any type". We should have each package register its types and then switch on @type to determine the type to marshal into.

For example, this type's name is "type.googleapis.com/google.devtools.cloudbuild.v1.BuildOperationMetadata"

**Comment by jba** [comment]
These clients are in maintenance mode. We don't plan to address this issue.

@pongad for the next generation of clients.
