### ISSUE TITLE
API version 4 not supported

### ISSUE THREAD

**Issue by OrenBochman** [google/google-api-go-client#141]
a new version of this API has been released and is as yet unsupported.

**Comment by adg** [comment]
Which API?

**Comment by OrenBochman** [comment]
Good point - google analytics api v4.0 
the requests are now posted via json query format, support for batches of queries, multiple dates ranges, multiple segments, calculated metrics etc ... https://developers.google.com/analytics/devguides/reporting/core/v4/

**Comment by mcgreevy** [comment]
It looks like this has now been added.  @OrenBochman can you confirm that this is what you're looking for:
https://github.com/google/google-api-go-client/blob/master/analyticsreporting/v4/analyticsreporting-gen.go

**Comment by rosekay69** [comment]
What is this
