### ISSUE TITLE
Please clarify the client's release (alpha/beta/ga) status

### ISSUE THREAD

**Issue by Capstan** [google/google-api-go-client#143]
The announce email refers to alpha versions of support for Go use of Google discovery-based APIs. AFAICT, the `User-Agent` refers to a 0.5 version which still seems like pre-release software. Please add a note to the front page with a clarification. If there's a roadmap for an overall release date, that'd be awesome to link to.

**Comment by zombiezen** [comment]
@jba

**Comment by zombiezen** [comment]
Sorry for the long response time on this one.  You can consider this beta, and we're going to update our docs to reflect this.

GA will come shortly, but I can't commit to a firm timeline yet.  We're fixing a couple odd edge cases (#177 and #139) that may break some folks that were already arguably broken, but those are the only blockers AFAIK.  We effectively treat any change in API as a bug, so this is a stable repository.
