### ISSUE TITLE
Introduce an interface instead of requiring a concrete *http.Client type

### ISSUE THREAD

**Issue by Dynom** [google/google-api-go-client#146]
To add more flexibility when it comes to HTTP clients, I propose to accept an Interface rather than a concrete type for the services.

An interface as suggested by @odeke-em in https://github.com/google/google-api-go-client/issues/142#issuecomment-225461252 and https://github.com/golang/go/issues/16047
```go
type HTTPClient interface {
    Do(req *http.Request) (res *http.Response, err error)
    Get(url string) (res *http.Response, err error)
    Post(urstring, bodyType string, body io.Reader) (res *http.Response, err error)
    PostForm(url string, values url.Values) (res *http.Response, err error)
    Head(url string) (res *http.Response, err error)
    // Add any other methods here if necessary
}
```

This would solve https://github.com/google/google-api-go-client/issues/142 and more issues as it would allow for more freedom in specifying (more robust) http clients. I'm more than willing to add a PR, if this project accepts public PR's.

**Comment by bradfitz** [comment]
I don't think this is a direction we want to take.

The http.RoundTripper interface already exists for defining your own transports. The *http.Client is a concrete type specifically to add helper methods (like PostForm) around an underlying HTTP transport.
