### ISSUE TITLE
Expose interface definitions

### ISSUE THREAD

**Issue by rgarcia** [google/google-api-go-client#148]
One nice thing that I've seen auto-generated Go clients provide is a package of interface definitions. E.g.,  the S3 library that AWS provides ([github.com/aws/aws-sdk-go/service/s3](https://godoc.org/github.com/aws/aws-sdk-go/service/s3)) has a corresponding S3 interface package ([github.com/aws/aws-sdk-go/service/s3/s3iface](https://godoc.org/github.com/aws/aws-sdk-go/service/s3/s3iface)). This makes mocking and dependency injection a lot nicer.

Is this something that `google-api-go-client` has considered doing?

**Comment by gmlewis** [comment]
Yes, it was attempted and abandoned.
https://code-review.googlesource.com/#/c/2971/
