### ISSUE TITLE
Generate a README for each package

### ISSUE THREAD

**Issue by broady** [google/google-api-go-client#150]
It should have a few things:
- godoc.org button
- Description of API (cribbed from the package level doc, maybe?)
- Support level for the package (i.e., alpha, etc)

**Comment by okdave** [comment]
On top of that, I wonder if we can improve the package doc too? It does have a quick description of the API and a brief getting-started section, but it's not great.

**Comment by jba** [comment]
Since this repo is in maintenance mode, we're not going to do this.
