### ISSUE TITLE
Bypass JSON encoding step in BigQuery

### ISSUE THREAD

**Issue by simonwistow** [google/google-api-go-client#151]
`bigquery.TableDataInsertAllRequestRows`requires a `Json` field of type `map[string]bigquery.JsonValue`.

However we're already receiving our data as JSON which means we have to decode it only for the SDK to re-encode it.

Is there any way to bypass the decoding/re-encoding step and pass in the JSON string directly?

**Comment by jba** [comment]
This BigQuery client is obsoleted by the one at [cloud.google.com/go/bigquery](https://godoc.org/cloud.google.com/go/bigquery). If this is still a problem for you, please open an issue there.

These clients are in maintenance mode. We don't plan on making any changes to them.
