### ISSUE TITLE
JSON decode error in drive/v2 API client

### ISSUE THREAD

**Issue by kujenga** [google/google-api-go-client#153]
We've recently started seeing the following error message in our production system in response to the execution of a Files.List call [1].

```
json: cannot unmarshal string into Go value of type float64
```

It seems that this has to be coming from the `FileImageMediaMetadata` decode, or the `FileImageMediaMetadataLocation` within it, as those are the only two applicable places where this could be. Has the v2 API changed in a breaking way? This only happens in a small number of cases, but it is a significant issue for us as it prevents continuing the iteration of the Files.List call. 

We're planning to switch to the v3 API, which will hopefully resolve this, but ideally this version of the API would work as well.

[1] https://godoc.org/google.golang.org/api/drive/v2#FilesListCall.Do
[2] https://godoc.org/google.golang.org/api/drive/v2#FileImageMediaMetadata
[3] https://godoc.org/google.golang.org/api/drive/v2#FileImageMediaMetadataLocation

**Comment by mattwhisenhunt** [comment]
Have you been able to instrument these errors to find out what values are being sent in these fields?

**Comment by kujenga** [comment]
Hey @mattwhisenhunt, I unfortunately don't recall the specifics of this issue. I believe that we migrated the system in which we were using the v2 API to v3, which eliminated these problems.

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.

@kujenga Thanks for creating the issue and responding today.
