### ISSUE TITLE
Some units are wrong in taskqueue comments

### ISSUE THREAD

**Issue by ianrose14** [google/google-api-go-client#154]
From the following file: google-api-go-client/taskqueue/v1beta2/taskqueue-gen.go

```
// EnqueueTimestamp: Time (in seconds since the epoch) at which the task
// was enqueued.
```

But this is wrong - the units are actually microseconds since epoch.

Also,

```
// LeaseTimestamp: Time (in seconds since the epoch) at which the task
// lease will expire. This value is 0 if the task isnt currently leased
// out to a worker.
```

Again, this is wrong, as the units are actually microseconds since epoch.

**Comment by mattwhisenhunt** [comment]
Thanks for opening this issue. This file is generated and it looks like by now has been replaced by cloudtasks.
