### ISSUE TITLE
sqladmin Operation with Status "DONE" has no EndTime

### ISSUE THREAD

**Issue by ccemeraldeyes** [google/google-api-go-client#156]
I'd expect that if an Operation has a "DONE" status, EndTime should be set, but e.g. Operation id b766cee5-fc8c-4a3a-959f-141314e58f71 does not. @broady

**Comment by broady** [comment]
As discussed offline, this library just passes on whatever came from the server, so this is an issue with the SQL admin API. 

Thanks!
