### ISSUE TITLE
IAM api rejects 48 character accountId/displayName

### ISSUE THREAD

**Issue by ccemeraldeyes** [google/google-api-go-client#159]
according to the docs, accountId is allowed to be 63 characters long, and displayName is allowed to be 100 bytes, yet the string "pcf-binding-cf397055-f228-4796-b2ca-55a667f59147" (48  @characters/bytes) when used for accountId and displayName is rejected with a 400 by the api. When this string is truncated to 20 characters the call works. @broady

**Comment by broady** [comment]
This is not an issue with the client itself, so please file wherever IAM takes issue requests.

As a coincidence, I used this package recently. I think this limit includes the `@project-id.iam.gserviceaccount.com` suffix.
