### ISSUE TITLE
Drop SetOpaque, use RawPath

### ISSUE THREAD

**Issue by broady** [google/google-api-go-client#161]
As of Go 1.5, we can use RawPath instead of SetOpaque.

It's used only to ensure Path isn't encoded, which is what RawPath is for.

```
// SetOpaque sets u.Opaque from u.Path such that HTTP requests to it
// don't alter any hex-escaped characters in u.Path.
func SetOpaque(u *url.URL) {
        u.Opaque = "//" + u.Host + u.Path
        if !has4860Fix {
                u.Opaque = u.Scheme + ":" + u.Opaque
        }
}
```

**Comment by broady** [comment]
cc @bradfitz

**Comment by okdave** [comment]
I made it halfway through this once (I cleaned up our URL templating code, but needed to plumb raw paths the whole way through).

**Comment by bradfitz** [comment]
Oh, I thought we could probably just modify that one SeOpaque function somehow (but probably renaming it). It got more involved than that, huh?

**Comment by okdave** [comment]
Yeah, I thought it was that simple but we need the encoded and un-encoded version of the path (to set `RawPath` to the former, `Path` to the latter). Currently the template package only produces the fully encoded version. 

I guess I could just un-encode it and set Path to it? That feels like a hack but it would work.

I was planning to make `uritemplates` produce both versions, which feels more cromulent.

Either way, this will be done by EoD.

**Comment by okdave** [comment]
@bradfitz @broady there are pending CLs here:
https://code-review.googlesource.com/#/c/7110/
https://code-review.googlesource.com/#/c/7111/
https://code-review.googlesource.com/#/c/7112/
