### ISSUE TITLE
Generated code calls Close() twice

### ISSUE THREAD

**Issue by mcellis33** [google/google-api-go-client#163]
In several places, `googleapi.CheckMediaResponse` calls `Close()` on the response body, then if `CheckMediaResponse` returns an error the error handling code calls `Close()` again.

[Here](https://github.com/google/google-api-go-client/blob/0637df23b94dd27d09659ae7d9052b6c8d6fc1a0/storage/v1/storage-gen.go#L5793) is one example.

According to the [io package documentation](https://godoc.org/io#Closer), the second call has undefined behavior.

In practice, there are transports that return response bodies that deadlock on the second `Close()` call.

**Comment by broady** [comment]
CheckMediaResponse:
https://github.com/google/google-api-go-client/blob/6dcd0d8ed711248e845137a35720e88b3ed2e04a/googleapi/googleapi.go#L149-L162

/cc @bradfitz 

Yeah, that's no good.

**Comment by bradfitz** [comment]
Should be harmless, but okay to fix too.
