### ISSUE TITLE
Can't clear a description from a Drive file

### ISSUE THREAD

**Issue by anachirino** [google/google-api-go-client#165]
Say you have a file with a description set, and you want to clear it.  It would be nice if you could clear it with:

			request := drive.File{}
			request.Description = ""
			resp, err := srv.Files.Patch(fileId, &request).Do()

But that does not work. I think it's due to Description being declared as:

    Description string `json:"description,omitempty"`

I think the encoded request will omit transmitting the description field.

**Comment by bradfitz** [comment]
The second line of:

```go
        request := drive.File{}
        request.Description = ""
```

Does nothing in Go. Because `""` is the zero value for a `string`, and `drive.File{}` returns a zero value of the struct with all fields set to their zero value.

You want to send `ForceSendFields` on the request struct.

**Comment by anachirino** [comment]
Thx!  Easy to miss.
