### ISSUE TITLE
TrafficPercentStrategyPercentages is an empty struct but is required to contain data

### ISSUE THREAD

**Issue by kyessenov** [google/google-api-go-client#168]
In an attempt to create a service using servicemanagement.v1 API, I create, enable, and submit a service config. Then, I need to create a rollout and specify percentages field (see https://cloud.google.com/service-management/reference/rest/v1/services.rollouts/create). However, the corresponding field has the type of an empty struct:
https://github.com/google/google-api-go-client/blob/master/servicemanagement/v1/servicemanagement-gen.go#L3927

Is there a way to pass map[string]int in place of Percentages field? Note that the fields for Percentages are dynamically generated using the service config IDs.

**Comment by mcgreevy** [comment]
It looks like map[string]int fields are not supported by the API generator, resulting in this empty struct.  I've started working on fixing this (https://code-review.googlesource.com/#/c/7790)

**Comment by kyessenov** [comment]
Thanks!
