### ISSUE TITLE
incorrect version identifiers: "v0.beta" instead of "beta"

### ISSUE THREAD

**Issue by vchudnov-g** [google/google-api-go-client#170]
It appears that maybe API/version combos of the form `foo/beta` might be creating Go libraries inside directories of the form `foo/v0.beta`. Is this intentional? If so, could you point me to all the transformation rules for version strings? If not intentional, uhm, could you fix?

Example: clouduseraccounts
https://www.googleapis.com/discovery/v1/apis/clouduseraccounts/v0.beta/rest is a 404
https://www.googleapis.com/discovery/v1/apis/clouduseraccounts/beta/rest exists and specifies its version as "beta"
and yet the versions available [here](https://github.com/google/google-api-go-client/tree/master/clouduseraccounts) are `v0.alpha`, `v0.beta`, `vm_alpha`, `vm_beta`.

Example: compute
Similar issue with 
https://www.googleapis.com/discovery/v1/apis/compute/v0.beta/rest (404) vs
https://www.googleapis.com/discovery/v1/apis/compute/beta/rest (version `beta`)
and yet the versions available [here](https://github.com/google/google-api-go-client/tree/master/compute) are `v0.alpha`, `v0.beta`, and `v1`.

**Comment by vchudnov-g** [comment]
And I can confirm that as recently as 2016-08-12, it was working (ie correct version directories), and I believe that it was working as well through 2016-09-20

**Comment by mcgreevy** [comment]
Yes, this is intentional.  See https://github.com/google/google-api-go-client/issues/78

The renaming is done here: https://github.com/google/google-api-go-client/blob/master/google-api-go-generator/gen.go#L320

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
