### ISSUE TITLE
incorrect links for beta APIs

### ISSUE THREAD

**Issue by dvyukov** [google/google-api-go-client#171]
See e.g:
https://godoc.org/google.golang.org/api/compute/v0.beta#InstancesService.GetSerialPortOutput
It says:

```
GetSerialPortOutput: Returns the specified instance's serial port output. For details, see https://cloud.google.com/compute/docs/reference/latest/instances/getSerialPortOutput
```

The link it wrong, it should point to https://cloud.google.com/compute/docs/reference/beta/instances/getSerialPortOutput

The latest version does not describe all parameters and return values of the call (I guess for some calls whole call can be missing in the latest version).

**Comment by jba** [comment]
Seems to be correct as of compute v1.
