### ISSUE TITLE
Consider retrying initial media upload requests.

### ISSUE THREAD

**Issue by mcgreevy** [google/google-api-go-client#172]
This change: https://code-review.googlesource.com/4501 removed the retry logic for non-resumable media upload requests.  This is because the media is read from the io.Reader source when the initial request is sent, and so the data is not available when we retry the request.

If we want to be able to retry these requests on failure, then we need to buffer the data.  We could reuse gensupport.MediaBuffer for this. The question is whether this extra memory usage due to the buffering is acceptable.

**Comment by jba** [comment]
Fixed by 9ed4ce5a42f74c2aeb21d02ba77ebd52a83f76e5.
