### ISSUE TITLE
cloudresourcemanager: how to tell if a project already exists?

### ISSUE THREAD

**Issue by mpl** [google/google-api-go-client#173]
Before creating a project, it would be useful to be able to tell if a project with the given project ID already exists.

I realize one way is to actually try to create the project and see if we get an error. But that is not really an option when, for example, pre-generating a pseudo-random project ID for the user, like the cloud console actually does.

I was expecting that if I get a ProjectsGetCall and I get a 403, I could interpret that as "the project already exist and someone else owns it", but apparently I'm getting a 403 even for projects that don't already exist, so no dice.

Is there a way to achieve that with cloudresourcemanager? If not, is there a way with another API/pkg?

**Comment by jba** [comment]
I don't know the answer, but it's unlikely you'll find it here. This repo holds automatically generated Go clients. We're just passing along the 403 from the underlying service.

**Comment by sir-buckyball** [comment]
The [cloudresourcemanager API](https://cloud.google.com/resource-manager/) does not provide a mechanism to check project_id availability. It also purposefully returns a `403` for Project GET operations to prevent id probing.

**Comment by mpl** [comment]
That's a bummer. So what is one supposed to do when creating a project and getting an error? Keep on retrying with new random names until not getting an error?

**Comment by sir-buckyball** [comment]
At present... yes.

I don't suppose you could elaborate on your use case? We have noticed many groups picking a prefix that they use for all projects.

**Comment by mpl** [comment]
@sir-buckyball oh, no problem. At https://camlistore.org/launcher we're deploying for users the Camlistore project on a gce instance that we create on their behalf. We now wanted to take advantage of the cloudresourcemanager API to even create the project for them (they had to do it by themselves as a prerequisite so far).

I did intend to prefix the project id with "camlistore-", and gen a random suffix, but that does not give a 100% guarantee that I'm going to generate one that is not already used. Hence why I wanted to check for its existence beforehand.

**Comment by sir-buckyball** [comment]
Would it be fair to treat your use case as a feature request of "don't require a project_id when creating a project"?

**Comment by mpl** [comment]
@sir-buckyball And the API takes care of generating/picking one from the available pool for me instead? sure, that works for us I guess. Even better, let us provide an optional prefix maybe, like for https://golang.org/pkg/io/ioutil/#TempFile ?

**Comment by sir-buckyball** [comment]
I've circulated your feedback with the team, but it's going to be a while before we can properly address your needs.

In the short term, checking for a `403` errors on create is the best you can do (and you'd need to do that anyways so long as your users provide a project_id).

**Comment by mpl** [comment]
@sir-buckyball thanks. feel free to rename the issue to match the feature request you suggested too. In the meantime, I think we'll indeed just let the users provide the project_id, even if we do create the project for them.

**Comment by mattwhisenhunt** [comment]
I'm going to close this old issue. If anybody wants to lobby for this change again please recreate on [Issue Tracker](https://issuetracker.google.com/components/187210/manage#basic).

**Comment by spew** [comment]
One thing you can do is a list request with a filter of "id:my-project-id". If the list request returns empty then you can be certain that one of the following is true:

1. You don't have authorization to list the project named "my-project-id".
2. There is no project with id "my-project-id".
