### ISSUE TITLE
"api/option" WithServiceAccountFile failing because of "grpc"

### ISSUE THREAD

**Issue by wenkesj** [google/google-api-go-client#174]
First of all, thank you for the useful API.

I want to use the "api/option" method `WithServiceAccountFile`, but when I do, I receive an indirect error from "grpc". I looked into it a little further and it seems that the grpc doc for [RoundRobin](https://godoc.org/google.golang.org/grpc#RoundRobin) and [WithBalancer](https://godoc.org/google.golang.org/grpc#WithBalancer) seem to be MIA from the exported methods? 

I am looking into it further as I keep seeing
> "This is the EXPERIMENTAL API and may be changed or extended in the future"

But all else aside, it could possibly be an issue on my end (alwayssss a possibility).

The stdout,
```
vendor/google.golang.org/api/option/option.go:130: undefined: grpc.RoundRobin
vendor/google.golang.org/api/option/option.go:131: undefined: grpc.WithBalancer
```

In my use case,
```go
client, err := storage.NewClient(context.Background(), projectId, option.WithServiceAccountFile(serviceKey))
if err != nil {
	return err
}
```

**Comment by wenkesj** [comment]
It seems to me that the [gRPC repo](https://github.com/grpc/grpc-go) is a bit ahead of the readme. 

The install command installs a previous tree of the source.
```sh
go get google.golang.org/grpc
```

Cloning and replacing is the best option for now.

**Comment by broady** [comment]
Use `go get -u google.golang.org/grpc/...`.

**Comment by wenkesj** [comment]
@broady do you think this may have been caused by my package manager?

**Comment by wenkesj** [comment]
Thanks for the update!

**Comment by broady** [comment]
Probably. Make sure all of the dependencies are up-to-date. There are 3-4 dependent repositories.
