### ISSUE TITLE
unable to go get "google.golang.org/api/compute/v1"

### ISSUE THREAD

**Issue by ctaggart** [google/google-api-go-client#175]
Since Friday, and on more than one computer, I've been unable to get the compute API. Any ideas what is wrong here? @vchudnov-g, I noticed a `regenerate all APIs` that day.

```
PS> go get "google.golang.org/api/compute/v1"
# cd C:\Users\c\go\src\google.golang.org\api; git pull --ff-only
fatal: Not a git repository (or any of the parent directories): .git
package google.golang.org/api/compute/v1: exit status 128
```

**Comment by ctaggart** [comment]
Apologies. I just had to clean out that directory in $GOPATH/src on the computers.

**Comment by leonardidouglas** [comment]
now i lost money in revshares

**Comment by leonardidouglas** [comment]
could i get this up and running and help with the cron job
