### ISSUE TITLE
ImageRawDisk.Sha1Checksum is ignored by Google API

### ISSUE THREAD

**Issue by ljfranklin** [google/google-api-go-client#181]
We're trying to set the `ImageRawDisk.Sha1Checksum` property when calling `computeService.Images.Insert(i.project, image).Do()` as follows:

```go
rawdisk := &compute.ImageRawDisk{
	Source: sourceURL,
	Sha1Checksum: sourceSha1,
}

image := &compute.Image{
	Name:        name,
	Description: description,
	RawDisk:     rawdisk,
}

operation, err := i.computeService.Images.Insert(i.project, image).Do()
if err != nil {
	return "", bosherr.WrapErrorf(err, "Failed to create Google Image")
}

if _, err = i.operationService.Waiter(operation, "", ""); err != nil {
	i.cleanUp(image.Name)
	return "", bosherr.WrapErrorf(err, "Failed to create Google Image")
}
```

We wrote a test where `sourceSha1` was set to "my-invalid-checksum" to verify that this operation would fail if the checksum was invalid, but we were surprised to see the Image creation succeed. After a bit more digging, it seems that the Golang SDK is setting the field correctly in the request but the Google backend API is apparently not using it. The following curl command also succeeds:

```bash
curl -vv -H 'Content-Type: application/json' -H 'Authorization: OAuth $AUTH_TOKEN' -X POST -d '{"name": "checksum-test-image", "rawDisk": {"source": "https://storage.googleapis.com/bosh-gce-raw-stemcells/bosh-stemcell-3312.7-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz", "sha1Checksum": "my-invalid-checksum"}, "sourceType": "RAW"}' https://www.googleapis.com/compute/v1/projects/<PROJECT_ID>/global/images?alt=json
```

This operation eventually succeeds when it should have failed due to a checksum mismatch (although `rawDisk.source` is unset in the final response):

```json
{
 "kind": "compute#image",
 "id": "...",
 "creationTimestamp": "2016-12-06T16:00:38.262-08:00",
 "name": "checksum-test-image",
 "description": "",
 "sourceType": "RAW",
 "rawDisk": {
  "source": "",
  "containerType": "TAR"
 },
 "status": "READY",
 "archiveSizeBytes": "416392642",
 "diskSizeGb": "3",
 "selfLink": "https://www.googleapis.com/compute/v1/projects/..."
}
```

We realize this is an issue with the backend, not the SDK so feel free to point us to a different spot to open an issue. Appreciate any help you can give!

**Comment by bradfitz** [comment]
Well, my guess was wrong. I thought maybe that field (sha1checksum) was marked as an output field in the resource, not an input field. But the JSON file's docs say:

>  An optional SHA1 checksum of the disk image before unpackaging; provided by the client when the disk image is created.

**Comment by jba** [comment]
The fact that the curl command fails means this isn't Go-specific. I've contacted the internal Google API team and will relay the answer.

**Comment by ljfranklin** [comment]
@jba any word from the API team? I realize it's holiday time and responses get delayed :)

**Comment by jba** [comment]
Current status is that it's a documentation bug. In other words, the feature is unimplemented. 

I will ping them to get confirmation.

**Comment by jba** [comment]
Confirmed: this is a doc bug. The doc will be updated to clarify.
