### ISSUE TITLE
Replace variant types with json.RawMessage

### ISSUE THREAD

**Issue by zombiezen** [google/google-api-go-client#183]
Similar to #177, variant types are just types that ought to defer unmarshalling.  At the moment, they are unmarshalled as `map[string]interface{}`, and then [`googleapi.ConvertVariant`](https://godoc.org/google.golang.org/api/googleapi#ConvertVariant) will simply marshal and unmarshal the map to bring it back to a struct.

This would be a breaking change, so this may not be worth the trouble, but I'm filing this as a bug per your request.  We can prioritize later.

**Comment by jba** [comment]
These clients are in maintenance mode. We don't plan to address this issue.

@pongad for the next generation of clients.
