### ISSUE TITLE
How do I do filter instances by metadata when I use `compute.instances.list`API

### ISSUE THREAD

**Issue by anarcher** [google/google-api-go-client#184]
I really want to filter instances by metadata. e.g. `metadata.layer=web`.How do I do filter instances by metadata when I use `compute.instances.list` API ? And Can I use `OR`? e.g.  `Status=RUNNING OR Status= PROVISIONING`

- https://cloud.google.com/compute/docs/reference/latest/instances/list

**Comment by broady** [comment]
The client will pass it straight through to the underlying API.

https://godoc.org/google.golang.org/api/compute/v1#InstancesService.List
https://godoc.org/google.golang.org/api/compute/v1#InstancesListCall.Filter

From reading the docs, it doesn't sound like it supports `OR`.
