### ISSUE TITLE
PerRPCCredentials superseded by OAuth2 source in transport.DialGRPC

### ISSUE THREAD

**Issue by danjacques** [google/google-api-go-client#186]
In [transport.DialGRPC](https://github.com/google/google-api-go-client/blob/b9d03e6e091e36f9a089515bc84cf14c2d199c4c/transport/dial.go#L84), the user may supply a set of `ClientOption`, some of which may, themselves, be gRPC [DialOption](https://godoc.org/google.golang.org/grpc#DialOption) via [WithGRPCDialOption](https://github.com/google/google-api-go-client/blob/b9d03e6e091e36f9a089515bc84cf14c2d199c4c/option/option.go#L124). One such gRPC option that can be provided is `PerRPCCredentials` via gRPC's [WithPerRPCCredentials](https://godoc.org/google.golang.org/grpc#WithPerRPCCredentials).

`DialGRPC` is explicitly aware of the [TokenSource](https://github.com/google/google-api-go-client/blob/b9d03e6e091e36f9a089515bc84cf14c2d199c4c/option/option.go#L31) option, and if no `TokenSource` is provided, it adds its own default token source to the PerRPCCredentials list. gRPC's `PerRPCCredentials` options are cumulative, and in the event that the user specifies their own `PerRPCCredentials` directly as a `DialOption`, `DialGRPC` will end up handing gRPC two `PerRPCCredentials` options, one for the default `TokenSource` that it forcefully adds and the other the user-supplied instance. This will, in turn, cause gRPC to include headers for both `PerRPCCredentials` instances, or fail if the default `TokenSource` is not functional (which may be why the user supplied their own credentials in the first place).

There should be a way for a user to provide `PerRPCCredentials` exclusively without a `TokenSource`. Perhaps the magic OAuth2 `TokenSource` handling should be removed, and the user made responsible for supplying all required credentials?

Note: one could supply their own gRPC connection directly via `WithGRPCConn`; however, this would side-step all of the nice default `ClientOption` setup that packages using `transport.DialGRPC` do, e.g., [datastore.NewClient](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/81b7822b1e798e8f17bf64b59512a5be4097e966/datastore/datastore.go#L101).

**Comment by jba** [comment]
If you use `option.WithoutAuthentication`, then `DialGRPC` won't add its own creds, and you should be able to use gRPC's creds option without conflict.
