### ISSUE TITLE
Google Analytics: can't find any sample code

### ISSUE THREAD

**Issue by dbaroncelli** [google/google-api-go-client#190]
I cannot find any sample code for using Google Analytics (to track specific server-side events in a Go application).
Can anyone add some sample code or maybe point to some existing samples?
Many thanks

**Comment by jaypanchal** [comment]
Isn't that still available?

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
