### ISSUE TITLE
Remove examples and update references to samples

### ISSUE THREAD

**Issue by lennrt** [google/google-api-go-client#192]
As you can see [here](https://github.com/google/google-api-go-client/blob/master/examples/pubsub.go#L278-L282) the `pubsub.go` example contains outdated information:
```
// This example demonstrates calling the Cloud Pub/Sub API. As of 20
// Aug 2014, the Cloud Pub/Sub API is only available if you're
// whitelisted. If you're interested in using it, please apply for the
// Limited Preview program at the following form:
// http://goo.gl/Wql9HL
```

The linked form no longer accepts responses.

**Comment by jba** [comment]
@broady should we delete the example, since this client is obsolete?

**Comment by broady** [comment]
We should probably delete all the samples.

README.md needs to be updated.

**Comment by lrudolph1** [comment]
If this client is obsolete, is there another alternative for Google App Engine apps running on the standard environment? I'd like to use the Pub/Sub API on a GAE app running on the standard environment, but  [this Google Cloud Platform reference](https://cloud.google.com/pubsub/docs/reference/libraries) says:

> we recommend using the older Google APIs Client Libraries if running on Google App Engine standard environment

**Comment by jba** [comment]
@anguillanneuf, FYI as you work on pubsub clients on GAE standard.
