### ISSUE TITLE
Generated client library for proto2 does not respect default fields

### ISSUE THREAD

**Issue by melissachang** [google/google-api-go-client#196]
Google Compute Engine protos are proto2. The automaticRestart field has default of true.

From the generated client library (https://raw.githubusercontent.com/google/google-api-go-client/master/compute/v1/compute-gen.go)

    AutomaticRestart bool `json:"automaticRestart,omitempty"`

This causes the following bug:
- My server sets automaticRestart to false
- Because of omitempty, automaticRestart is passed over the wire with no value
- GCE server sees automaticRestart with no value and uses true

Seems like omitempty should not be there, at least for fields with default values that are not the normal default.

@zombiezen

**Comment by jba** [comment]
@zombiezen, IIRC there's an `unfortunateDefault` function that might need tweaking...

**Comment by zombiezen** [comment]
@adams-sarah Would you be willing to do this?  Happy to share state.

**Comment by adams-sarah** [comment]
Ya, SGTM.

**Comment by jba** [comment]
We can force the field to be a `*bool` instead of a `bool`. https://code-review.googlesource.com/c/13113.

@melissachang when this happens, your code will break: you'll need to pass a pointer to a false value. Here is a [helper](https://godoc.org/google.golang.org/api/googleapi#Bool) for that.

**Comment by danawillow** [comment]
Just curious what the long-term plan for this sort of fix is. Is it to eventually get rid of `ForceSendFields` (which accomplishes the same thing without having to change any apis)? If so, it would be great to see one big change that adds all of the non-nil-as-default fields to that list to avoid inconsistencies between the various APIs.

(also, this change only affects v1 apis. shouldn't alpha and beta be included as well?)

**Comment by jba** [comment]
You're right that `ForceSendFields` would work, but we wanted a better developer experience for this widely-used API. Apologies for the disruption.

We have no official policy on this, but I think for lesser-used APIs we'd recommend `ForceSendFields`.

Regarding the alpha and beta versions: I naively assumed that everyone was on v1. I did get a bug report for beta and fixed that. I'll do alpha too.

**Comment by jba** [comment]
https://code-review.googlesource.com/14253
