### ISSUE TITLE
Compute: can't create InstanceGroupManager with 0 instances

### ISSUE THREAD

**Issue by tmshn** [google/google-api-go-client#197]
I know this is duplicate of #54 (and there may be lots of issues of same cause), but it's closed 2 years ago, so I opened the new one.

## What is the problem?

Can't create InstanceGroupManager with 0 instances.

When one try to insert an instance group manager with `targetSize = 0`, like as follows:
```go
manager := &compute.InstanceGroupManager{
	Name:             "test-group",
	BaseInstanceName: "test-instance",
	InstanceTemplate: "projects/test-project/global/instanceTemplates/test-template",
	TargetSize:       0,
}
```

The marshaled JSON does not contain `"targetSize"` field, which is required, because the **omitempty** option is specified. Thus, the insertion request will fail.

## How should it be solved?

Maybe there're 2 options:
1. Changed type of `TargetSize` field from `int64` to `*int64`, as done in #54 
2. Remove `omitempty` option

Either of them will lead to the backward-incompatible change, but IMHO, 2nd choice look to have less impact.

**Comment by bradfitz** [comment]
Cases like this is why  `ForceSendFields` was added. Does that work for you?

**Comment by tmshn** [comment]
@bradfitz Thank you for the information! Setting `ForceSendField` WORKED for me! 👏 
I need to read the docs more carefully...
