### ISSUE TITLE
Documentation code for monitoring.Empty is not well aligned

### ISSUE THREAD

**Issue by Bo0mer** [google/google-api-go-client#200]
The documented code for `monitoring.Empty` is not well aligned (see [1], [2]). I do not know whether this is problem with the code itself or with the tool that generated it.

I believe that the whole example code should be indented once more.

Regards,
Ivan

[1] https://godoc.org/google.golang.org/api/monitoring/v3#Empty
[2] https://github.com/google/google-api-go-client/blob/master/monitoring/v3/monitoring-gen.go#L488-L491

**Comment by jba** [comment]
Thanks for the report. It's an issue with the code generator. It needs to do a better job of scrubbing the descriptions it gets from the discovery doc.

**Comment by jba** [comment]
@pongad, assigning this to you so it can be dealt with in the new code generator.

**Comment by jba** [comment]
These clients are in maintenance mode. We don't plan to address this issue.

@pongad for the next generation of clients.
