### ISSUE TITLE
Update compute-api.json and compute-gen.go

### ISSUE THREAD

**Issue by maurofaccenda** [google/google-api-go-client#206]
There are new features on API v1, such as Instance setLabels (https://cloud.google.com/compute/docs/reference/v1/instances/setLabels), but to use it compute-api.json and compute-gen.go need to be updated.

**Comment by jba** [comment]
I believe that's been in the actual repo for a couple of days at least (so `go get -u` should have fetched it).

I just mirrored to this repo.
