### ISSUE TITLE
Google Analytics v4 example

### ISSUE THREAD

**Issue by sudo-suhas** [google/google-api-go-client#207]
I am interested in contributing an example for `analyticsreporting/v4` with jwt auth. Would a port of the official examples([java](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-java), [python](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-py)) be a good idea?

**Comment by jba** [comment]
@cbro @rakyll

**Comment by rakyll** [comment]
What about starting with the hello world sample, see Java's here: https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-java.

**Comment by sudo-suhas** [comment]
@rakyll I was suggesting that as well.

**Comment by sudo-suhas** [comment]
On second thought, contributing to this repo is too complicated. And I am not sure how the analytics example will fit into the existing ones.

Here's the example as a separate repo if someone comes across this thread - https://github.com/sudo-suhas/example-analyticsreporting
