### ISSUE TITLE
Scheduling:AutomaticRestart is now a *bool , instead of a bool

### ISSUE THREAD

**Issue by tpoindessous** [google/google-api-go-client#208]
Hi

I think there is an error in comppute-gen.go, in line 10298 :
```
	AutomaticRestart *bool `json:"automaticRestart,omitempty"`
```

AutomaticRestart is now a *bool instead of a bool.

This is the only one occurence of *bool, so I think this is a mistake.

Can you correct it please and update this repo ?

Thanks !

**Comment by jba** [comment]
We did this deliberately to deal with the problem described in #196. You can use [this convenience function](https://godoc.org/google.golang.org/api/googleapi#Bool) to set the field.
