### ISSUE TITLE
Missing method or Wrong example

### ISSUE THREAD

**Issue by simon-s9** [google/google-api-go-client#209]
There is something wrong with the `compute` api. I cannot see a single method there, especially the `Insert` method which is mentioned [here](https://github.com/google/google-api-go-client/blob/master/examples/compute.go#L95).

**Comment by adams-sarah** [comment]
Can you be more specific?
What are you trying to do? Code samples are helpful.

**Comment by simon-s9** [comment]
Sorry, It was my IDE that went mad. Everything seems to be fine. Sorry again for bothering.
