### ISSUE TITLE
GitHub mirror is 5 commits behind the upstream repository.

### ISSUE THREAD

**Issue by shurcooL** [google/google-api-go-client#210]
It seems there's some issue with the mirroring, the github repo's [latest commit](https://github.com/google/google-api-go-client/commits/master) is from 18 days ago:

![image](https://user-images.githubusercontent.com/1924134/27488929-c74dfdf0-5806-11e7-99a2-057004f594e0.png)

But the real upstream repository has [5 commits](https://code.googlesource.com/google-api-go-client/+log/HEAD) since then:

![image](https://user-images.githubusercontent.com/1924134/27489009-0004e866-5807-11e7-89f7-71898e430ac0.png)

I spotted this while investigating https://github.com/golang/gddo/issues/491. /cc @DavidVaini

**Comment by bradfitz** [comment]
Actually I forget what handles mirroring this.

All the Go repos are mirrored by x/build/cmd/gitmirror (née "watcher"), with debug URL here:

https://farmer.golang.org/debug/watcher/

But it only does go.googlesource.com repos.

google-api-go-client is on code.googlesource.com.

/cc @andybons @jba @rakyll @broady

**Comment by broady** [comment]
I'll set up the same repo syncer for the cloud.google.com/go (google-cloud-go) repo.

**Comment by bradfitz** [comment]
In a separate GCP project?

**Comment by broady** [comment]
I'm going to put it in the same project.

http://go-cloud-reposync.appspot.com/status

Just started refactoring to allow multiple syncers at once:
https://github.com/broady/reposync/commit/e1d1170428e40931ea982b67ac8ae43479d2b667

(yeah, I know a lot of this is basically duplicated from gitmirror, but quite a bit more simple (no dashboard, assumptions of gerrit, etc)

**Comment by broady** [comment]
It's set up.
