### ISSUE TITLE
go get github.com/google/google-api-go-client/tree/master/urlshortener/v1 failed

### ISSUE THREAD

**Issue by nagerenshifou** [google/google-api-go-client#213]

**Comment by adams-sarah** [comment]
This is the wrong import path.
Note the /tree/master/ in the middle - this is for the github UI.

The correct import path (explained on the Readme, though probably not as clearly as it could be):
google.golang.org/api/urlshortener/v1

so, `go get google.golang.org/api/urlshortener/v1`
