### ISSUE TITLE
Subscription CancelReason 0-value can't be distinguished

### ISSUE THREAD

**Issue by karlkeefer** [google/google-api-go-client#215]
If you check CancelReason for a non-canceled receipt, it will appear it was canceled by the user.

The property for `CancelReason` needs to be a pointer if we want to have a meaningful distinction between `0` and `not set`

https://github.com/google/google-api-go-client/blob/master/androidpublisher/v2/androidpublisher-gen.go#L2012-L2017

**Comment by karlkeefer** [comment]
I just realized the same issue also applied to paymentState in the same struct!

**Comment by karlkeefer** [comment]
Thanks @jba !

**Comment by hassansin** [comment]
@jba We are still seeing this in v3, `CancelReason` is int64 instead of a pointer.

**Comment by jba** [comment]
@jadekler
