### ISSUE TITLE
Request for Instance ID service support

### ISSUE THREAD

**Issue by chemidy** [google/google-api-go-client#216]
Is it possible to have a client for Instance ID Service ?

https://developers.google.com/instance-id/reference/server#manage_relationship_maps_for_multiple_app_instances

**Comment by jba** [comment]
Looking into it. It won't be anytime soon, unfortunately.

**Comment by jba** [comment]
This API does not provide a public discovery document (see https://www.googleapis.com/discovery/v1/apis for a complete list). The code generator for the clients in this repo only supports APIs that do so.
