### ISSUE TITLE
support gzip responses

### ISSUE THREAD

**Issue by DexterHaslem** [google/google-api-go-client#219]
currently the 'Do()' functions in services assume response bodies are in json which fails if gzip responses are enabled. (set by client 'Accept-Encoding' and 'User-Agent' headers containing gzip)

Please add support for gzip'd responses

**Comment by bradfitz** [comment]
Show code with the actual problem.

The Go HTTP client does gzip transparently. The upper level calling code (google-api-go-client) does not need to be aware of it.

**Comment by DexterHaslem** [comment]
Hi Brad, thanks for the reply.

Here is an example you could stick eg, in the bottom of the quickstart example instead of the label stuff:
```
	srv, err := gmail.New(client)
	if err != nil {
		log.Fatalf("Unable to retrieve gmail Client %v", err)
	}

	srv.UserAgent = "Some Browser 1.0 gzip"
	mailID := "15d571eadefa1116" // replace with a good mail ID you have handy
	r := srv.Users.Messages.Get("me", mailID)
	r.Header().Add("Accept-Encoding", "gzip")
	m, err := r.Do()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%+v\n", m)

```

it will log fatal with something like 
> 2017/07/19 19:57:19 invalid character '\x1f' looking for beginning of value

coming from json.NewDecoder being called directly on the response body in Do()

**Comment by bradfitz** [comment]
Ah, I see. The short answer is you're not supposed to do that. The default Go http.Transport already adds that header (and removes the response header + transparently un-gzips the response, when needed), but it only does that magic if the caller code didn't do it itself.

In this case, you're doing it yourself, (via a backdoor the google-api-go-client gives you for unrelated reasons), so it's not transparently uncompressing the response, confusing the google-api-go-client code.

So, don't do that.

Maybe this bug can track making the google-api-go-client package detect if you've done that and return an error instead saying "Don't do that".

**Comment by DexterHaslem** [comment]
Ok, thanks for the clarification. Is there currently a `right way` to enable or force gzip in the generated api services?  I was trying to follow the performance guide for Gmail ( https://developers.google.com/gmail/api/guides/performance ) after realizing nothing is currently being gzipped (and not in sent in either header).

**Comment by jba** [comment]
> Maybe this bug can track making the google-api-go-client package detect if you've done that and return an error instead saying "Don't do that".

Challenge accepted. Does "that" mean balking at any attempt to set "Accept-Encoding"? Any other headers you want to forbid while we're at it?

**Comment by bradfitz** [comment]
I think any `Accept-Encoding` is best.

**Comment by DexterHaslem** [comment]
@bradfitz can you point me to the code where gzip is added to the transport automatically?

The client headers being sent by gmail api client never have `Accept-Encoding`, only the go client user agent and authorization, so I'd like to see if there is some sort of criteria I'm not meeting for it to turn on

**Comment by bradfitz** [comment]
Public docs are https://golang.org/pkg/net/http/#Transport.DisableCompression

Code is in src/net/http/transport.go.

**Comment by DexterHaslem** [comment]
Thanks, that set me on the right path. For what it's worth after a bit of debugging the actual code executed was here https://github.com/golang/go/blob/master/src/net/http/h2_bundle.go#L7252

So in case anyone else makes the same mistake as I did following the google performance page,
the take away is to adjust *only* the user agent and google will send gzip responses back.

**Comment by bradfitz** [comment]
Some Google services use a blacklist of User-Agent values (for user-agents known to be buggy with gzip). But some use a whitelist. From my understanding, a number are in the process of moving from a whitelist to a blacklist now, so gzip will work by default even with custom user-agents.

**Comment by DexterHaslem** [comment]
OK, that is great to know, thanks!
