### ISSUE TITLE
Include CurrentNodeCount on NodePool struct

### ISSUE THREAD

**Issue by montanaflynn** [google/google-api-go-client#223]
Currently the `NodePool` struct only includes `InitialNodeCount` which may have been changed. The `Cluster` struct includes both `InitialNodeCount` and `CurrentNodeCount`.

This is inside [container/v1/container-gen.go](https://github.com/google/google-api-go-client/blob/master/container/v1/container-gen.go)

**Comment by jba** [comment]
The container service API doesn't provide this field. In other words, it's an issue with the underlying service, not this client, which is auto-generated from a service description.

Contact https://cloud.google.com/support or another forum and reference https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters.nodePools.
