### ISSUE TITLE
Add option.ClientOption to support additional wrapping of http.RoundTripper in OAuth http.Client

### ISSUE THREAD

**Issue by jkowalski** [google/google-api-go-client#224]
I need to limit upload speeds when sending potentially large amounts of data to Google Cloud Storage using `cloud.google.com/go/storage`.

I could not find any official API to support throttling, so I'm currently achieving this is by using custom `http.RoundTripper` and replacing req.Body with a "slow" reader (based on excellent `github.com/efarrer/iothrottler` for all cloud uploads).

I could not find a way to override http.RoundTripper on the HTTP Client created internally by `cloud.google.com/go/storage`, other than creating the entire client by hand and passing it using `option.WithHTTPClient`. The problem is that setting up OAuth2 client and is a major pain (there is `google.golang.org/api/transport` which is very nice, but not meant to be used by applications).

It would be great if there was a option.ClientOption to wrap the HTTP RoundTripper via a callback. The API would take a callback function:

```go
func WithHTTPRoundTripper(func(rt http.RoundTripper) http.RoundTripper) ClientOption {
}
```

The function would be called as part of setting up HTTP Client in google.golang.org/api/transport.
I'll be happy to send a CL to implement this feature if it's found useful (I'm a Googler).

The benefit would be going from the following code (brittle, relies on unsupported API):

```go
ctx := context.Background()
throttler := iothrottler.NewIOThrottlerPool(200000 * iothrottler.BytesPerSecond)

// NOTE: this is technically not a supported API, but setting up OAuth2 auth is a pain.
hc, _, err := transport.NewHTTPClient(ctx,
    option.WithScopes(storage.ScopeFullControl),
    option.WithUserAgent("throttling-demo"),
)
if err != nil {
    log.Fatalf("can't create HTTP client: %v", err)
}

// override round-tripper to use throttling.
hc.Transport = newThrottlingRoundTripper(hc.Transport, throttler)

st, err := storage.NewClient(ctx, option.WithHTTPClient(hc))
```

to this code (clean):

```go
ctx := context.Background()
throttler := iothrottler.NewIOThrottlerPool(200000 * iothrottler.BytesPerSecond)

st, err := storage.NewClient(ctx, option. WithHTTPRoundTripper(func(rt http.RoundTripper) http.RoundTripper {
  return newThrottlingRoundTripper(rt, throttler)
}))
```

**Comment by jba** [comment]
No objections, but let's have @zombiezen @broady @rakyll @adams-sarah weigh in.

**Comment by broady** [comment]
That's an interesting idea, but isn't it possible to wrap the writers? That is...

```diff
diff --git a/storage/objects/main.go b/storage/objects/main.go
index b7892ec..2045557 100644
--- a/storage/objects/main.go
+++ b/storage/objects/main.go
@@ -17,6 +17,8 @@ import (
        "os"
        "strings"

+       "github.com/efarrer/iothrottler"
+
        "google.golang.org/api/iterator"

        "golang.org/x/net/context"
@@ -24,6 +26,8 @@ import (
        "cloud.google.com/go/storage"
 )

+var throttle = iothrottler.NewIOThrottlerPool(200000 * iothrottler.BytesPerSecond)
+
 func main() {
        projectID := os.Getenv("GOOGLE_CLOUD_PROJECT")
        if projectID == "" {
@@ -87,7 +91,8 @@ func write(client *storage.Client, bucket, object string) error {
        }
        defer f.Close()

-       wc := client.Bucket(bucket).Object(object).NewWriter(ctx)
+       var wc io.WriteCloser = client.Bucket(bucket).Object(object).NewWriter(ctx)
+       wc, err = throttle.AddWriter(wc)
        if _, err = io.Copy(wc, f); err != nil {
                return err
        }
```

**Comment by jkowalski** [comment]
Let me double check, but I believe this only delays the upload (until the writer Close has been called) and does not make the actual upload any slower (it's a quick unthrottled burst once the file is complete).

**Comment by jkowalski** [comment]
Confirmed - the writer is somehow buffered, while overriding http.RoundTripper has the correct behavior.

**Comment by broady** [comment]
I'm concerned about adding more API surface that makes assumptions about the underlying transport/implementation.

When (if?) this API moves to a gRPC transport, RoundTrippers are less meaningful.

I'd rather figure out how to solve your problem (which I still don't fully understand). Do you want to rate limit for QoS reasons?

**Comment by jkowalski** [comment]
My scenario is a backup tool that copies data from a NAS to the cloud, typically running in a home/office LAN connected over relatively slow network connection (dsl/cable, usually asymmetric). I don't want to use up all possible upload bandwidth, because that tends to severly impact other clients' ability to download/upload. Given that full (non-incremental) backups can be quite large, we're talking about TBs of data that need to be pushed through so that can't really be done quickly.

**Comment by zombiezen** [comment]
[storage.Writer](http://godoc.org/cloud.google.com/go/storage#Writer) documents that it will send data in sized chunks, with a reasonable default set.  Does changing `Writer.ChunkSize` help you?

How large are the individual objects you are writing?

**Comment by jkowalski** [comment]
The chunks are relatively large O(20MB) and I need to upload them in a slow but steady fashion (for example average 5Mbit/s on a 10Mbit/s cable) instead of unthrottled spikes that are spread apart.

**Comment by jba** [comment]
We've added a [NewTransport](https://godoc.org/google.golang.org/api/transport/http#NewTransport) function that should do it. Reopen if it's still a problem.

**Comment by markmssd** [comment]
@jba could you provide an example of how to use  `NewTransport` to mix `option.Options`?

I'm trying to use the Storage API as such:

```
ctx := context.Background()
credsOpts := option.WithCredentialsJSON([]byte(os.Getenv("GCLOUD_SERVICE_KEY")))
transport := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
client := &http.Client{Transport: transport}
clientOpts := option.WithHTTPClient(client)

storageClient, err := storage.NewService(ctx, credsOpts, clientOpts)
```

I've also tried using the `NewTransport` by passing in my `credsOpts`, then creating a `Client` with it, but in vain.

It keeps failing with `Reason: required, Message: Login Required`, as if the credentials we're being lost along the way.

Thanks!

**Comment by jschaf** [comment]
I had success with the Sheets API using the below code. The difference from your code is the `googhttp.NewTransport` call which wires up the RoundTripper with the appropriate auth.

```go
import (
	googhttp "google.golang.org/api/transport/http"
)

func main() {
	loggingTransport := myCustomTransport()
	transport, err := googhttp.NewTransport(ctx, loggingTransport, option.WithCredentials(creds))
	if err != nil {
		return fmt.Errorf("new transport: %w", err)
	}
	httpClient := &http.Client{
		Transport: transport,
	}
	sheetSvc, err := sheets.NewService(ctx, option.WithCredentials(creds), option.WithHTTPClient(httpClient))
	if err != nil {
		return fmt.Errorf("new sheets service: %w", err)
	}
}
```


Using option.WithHTTPClient without using googhttp.NewTransport won't work because WithHTTPClient bypasses the normal credential logic.

https://github.com/googleapis/google-api-go-client/blob/main/transport/http/dial.go#L45
```go
func NewClient(ctx context.Context, opts ...option.ClientOption) (*http.Client, string, error) {
	// omitted
	if settings.HTTPClient != nil {
		return settings.HTTPClient, endpoint, nil
	}
	trans, err := newTransport(ctx, defaultBaseTransport(ctx, clientCertSource), settings)
	if err != nil {
		return nil, "", err
	}
	return &http.Client{Transport: trans}, endpoint, nil
}
```

### References
- [StackOverflow: Use custom HTTP client with Google's API go library?](https://stackoverflow.com/questions/69978463/use-custom-http-client-with-googles-api-go-library)

> Because WithHTTPClient rules out the use of any other option, the alternative is to prepare the http client with the token source. To achieve that, the transport needs to be defined.

```go
service, err := ggoauth2.NewService(
    ctx,
    option.WithHTTPClient(&http.Client{
        Timeout: 30 * time.Second,
        Transport: &oauth2.Transport{
            Base:   http.DefaultTransport,
            Source: tokenSource,
        },
    }),
)
```
