### ISSUE TITLE
BigQuery async query standard SQL bug

### ISSUE THREAD

**Issue by hamaxx** [google/google-api-go-client#225]
When submitting async query to bigquery UseLegacySql flag is ignored when set to false. This happens because the option is not a pointer and json tag on JobConfigurationQuery is set to omitempty.

As a result it's impossible to make an async standard SQL query.

Code example:

	jobConfigQuery := &bigquery.JobConfigurationQuery{
		Query:             queryStr,
		UseLegacySql:      false,
	}

	job := &bigquery.Job{Configuration: &bigquery.JobConfiguration{Query: jobConfigQuery}}

	runningJob, err := bq.service.Jobs.Insert("my-project", job).Do()

	// Result:
	// Bigquery job errors: [{"location":"query","message":"2.1 - 95.1: Unrecognized token UNION.\n[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)]"

**Comment by adams-sarah** [comment]
Hey @hamaxx, it looks like you are using the generated bigquery client.
This one (cloud.google.com/go/bigquery) supports the functionality you require.
It is in beta, though we do not intend to make many more breaking changes before it goes GA.

Can you use this API instead?

**Comment by adams-sarah** [comment]
cc @jba

**Comment by hamaxx** [comment]
We'll migrate to the new client as soon as possible. Until then I just copied the bigquery client file to our code base and added the missing pointer. Hopefully we'll migrate to the new client before this becomes a problem.

**Comment by jba** [comment]
You can also set `jobConfigQuery.ForceSendFields` to `[]string{"UseLegacySql"}`.
