### ISSUE TITLE
Drive v3 Q for parents not working

### ISSUE THREAD

**Issue by zwerch** [google/google-api-go-client#227]
Hello there,

I am currently running into some issues regarding the v3 API.

I'm using a service account and listing all my files worked so far. Now I'm trying to build a folder tree to later display it to the user. I can't seem to figure out how to display only the content of one folder.

Minimal _working_ example:
```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"

	"golang.org/x/net/context"
	"golang.org/x/oauth2/google"
	"google.golang.org/api/drive/v3"
)

func main() {
	ctx := context.Background()

	configFile, err := ioutil.ReadFile(os.Getenv("GOOGLE_SERVICE_ACCOUNT_JSON_FILENAME"))
	if err != nil {
		log.Fatalf("Unable to read service account json file: %v", err)
	}
	jwtConfig, err := google.JWTConfigFromJSON(configFile, drive.DriveScope)
	if err != nil {
		log.Fatalf("Unable to retrieve JWT Config %v", err)
	}
	jwtConfig.Subject = os.Getenv("GOOGLE_DRIVE_USER_ACCOUNT_EMAIL")
	client := jwtConfig.Client(ctx)

	driveService, err := drive.New(client)
	if err != nil {
		log.Fatalf("Unable to retrieve drive Client %v", err)
	}

	nextPageToken := ""
	fileList, err := getDriveFileList(driveService, nextPageToken)
	for fileList.NextPageToken != "" {
		if err != nil {
			log.Fatalf("Unable to retrieve files: %v", err)
		}
		for _, file := range fileList.Files {
			fmt.Println(file.Parents, file.Id, file.Size, file.ModifiedTime, file.Name, file.Permissions)
		}
		nextPageToken = fileList.NextPageToken
		fileList, err = getDriveFileList(driveService, nextPageToken)
		fmt.Println("Next page")
	}
}

func getDriveFileList(driveSvc *drive.Service, nextPageToken string) (*drive.FileList, error) {
	// return driveSvc.Files.List().Fields("nextPageToken, files(parents, id, name, size, webContentLink, permissions, modifiedTime)").OrderBy("folder, modifiedTime desc, name").PageToken(nextPageToken).Do()
	// return driveSvc.Files.List().Fields("nextPageToken, files(parents, id, name, size, webContentLink, permissions, modifiedTime)").OrderBy("folder, modifiedTime desc, name").PageToken(nextPageToken).Q("'root' in parents").Do()
	// return driveSvc.Files.List().Fields("nextPageToken, files/*").Q("'[censored]' in parents").PageToken(nextPageToken).Do()
	return driveSvc.Files.List().Fields("nextPageToken, files(parents, id, name, size, webContentLink, permissions, modifiedTime)").Q("'root' in parents").PageToken(nextPageToken).Do()
}
```

Only the first commented line works, without the Q.

I got the parent ID from another call, also tried programmatically handing over the ID, didn't seem to work either.
The issue seems to be in the call of the Q method. I already tried many things there, like using aliases and so on. It seems not to work when filtering for the parent ID. Can you tell me what I'm doing wrong here or did I just find some weird bug? I'd really appreciate some intel here.

Best regards,
Robin

**Comment by gmlewis** [comment]
The second commented line seemed to work fine for me... only the 3rd commented line returned `Error 404: File not found`, but I'm guessing that I don't have any files that match the `[censored]` query.

Can you please post the error messages that you are seeing in order to better help you debug this?

**Comment by zwerch** [comment]
Hello @gmlewis, thanks for your answer and your time.

The thing is, none of the query does return an error at all. Sorry I didn't specify that fact. It just returns an empty list, which is not correct because I can see files with these parent IDs when getting the whole file list. And there are definitely files in my `root` folder, which are not displayed in my case. Maybe the issue is related to anything else? But how can I see the whole file list but not the queried / filtered then?

**Comment by gmlewis** [comment]
I'm not sure I fully understand the problem, but to directly answer the one question:

> But how can I see the whole file list but not the queried / filtered then?

I tried this, which seemed to work:

```go
return driveSvc.Files.List().Fields("nextPageToken, files/*").PageToken(nextPageToken).Do()
```

In other words, omit the query part to see the whole file list.  Does that help?

If this is not helpful, maybe you could describe how to duplicate the problem... something like:
"Create 3 files, named X, Y, and Z, with contents XC, YC, ZC, then run this query...". I'm going to need lots of details in order to try and reproduce the problem. If you want to take this offline, maybe you could put the details in a GitHub gist or some pastebin possibly.

**Comment by zwerch** [comment]
I'm sorry I obviously wasn't clear enough.

So, to clarify, here's what works for me:
- the unfiltered file list (without the `Q` method anywhere in the chain)
- the filtered file list (with `Q("mimeType='application/vnd.google-apps.folder'")`)

What does not work (just returning an empty list, but no error):
- the filtered file list (with `Q("'root' in parents")`)
- the filtered file list (with `Q("'[some_id]' in parents")`, where `[some_id]` is the root folder fileID or another fileID I got from the unfiltered query)

I'm sorry I cannot provide you with better duplication steps because the account is not mine, I don't have full access to it, I just provided a friend (whose account this is) with instructions on how create this service account and how to allow the API access.
Also my code base for this project currently only contains the snippet I already posted initially, nothing more, nothing less.

**Comment by gmlewis** [comment]
OK, it sounds to me like this really isn't a client issue at all... it is a Drive API issue and getting the query right.

In cases like these, I highly recommend playing around with the [Google API explorer](https://developers.google.com/apis-explorer/#p/drive/v3/drive.files.list) and discovering what queries work for your situation and then copying over those queries into your client code.

https://developers.google.com/apis-explorer/#p/drive/v3/drive.files.list

Having said that, the `Q("'root' in parents")` query works fine for me as originally written and I get back a large number of results.
Good luck to you... sorry I couldn't help more.

**Comment by zwerch** [comment]
Too bad. I'm gonna try to figure it out though. Thanks a lot anyway @gmlewis!
