### ISSUE TITLE
serviceuser v1 api: can't list enabled services for a project

### ISSUE THREAD

**Issue by tve** [google/google-api-go-client#228]
I'm trying to list the enabled APIs for a project and am failing. The API call I'm trying to make is https://cloud.google.com/service-management/reference/rest/v1/services/list with the consumerID query string param set to "project:<project-id>". I'm calling `https://cloud.google.com/service-management/reference/rest/v1/services/list` (https://godoc.org/google.golang.org/api/serviceuser/v1#ProjectsServicesService.List) passing the project ID in, but I get the following error:
```
<p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1/project:project-id-3416666172000000000/services?alt=json</code> was not found on this server.  <ins>That’s all we know.</ins>
```
From my reading of the API docs, the URL should be:
```
/v1/services?consumerID=project:project-id-3416666172000000000
```
Am I doing something wrong or is there a bug?

**Comment by tve** [comment]
I found a resolution, in the source code I saw https://github.com/google/google-api-go-client/blob/master/serviceuser/v1/serviceuser-api.json#L122 which states how the project ID needs to be passed in, but this comment doesn't make it into the docs at https://godoc.org/google.golang.org/api/serviceuser/v1 (unless I'm blind).

**Comment by tve** [comment]
I see that the documentation for the "name" parameter in the ProjectsServicesService.Enable call is similarly absent from the godoc and it's impossible to divine what needs to be passed from any docs I see.

**Comment by mattwhisenhunt** [comment]
Okay, I think I found part of the problem. There are two APIs: Service User and Service Management.
What threw me off for a while is that the Service User API's definition (what is used to generate client code and Go Docs) points to the documentation for Service Management.

It sounds like you are looking for https://godoc.org/google.golang.org/api/servicemanagement/v1

**Comment by jba** [comment]
Assuming from lack of response that your problem is resolved. Reopen otherwise.
