### ISSUE TITLE
Using GO it's impossible to set ViewersCanCopyContent to false

### ISSUE THREAD

**Issue by FabioIngrao** [google/google-api-go-client#229]
file: drive-gen.go
package drive // import "google.golang.org/api/drive/v3"

type File struct {
 ....

// ViewersCanCopyContent: Whether users with only reader or commenter
	// permission can copy the file's content. This affects copy, download,
	// and print operations.
	ViewersCanCopyContent bool `json:"viewersCanCopyContent,omitempty"`
}

When you create or update a file, ViewersCanCopyContent is serialized **only** if it's set to true.
This means that you cannot set "Restrict download, print & copy actions on this file for commenters & viewers" using the GO library, since this option requires ViewersCanCopyContent to be false.

I "fixed" this issue by removing 'omitempty', but that makes the default on create/update the opposite of what one expects.

**Comment by jba** [comment]
Try this:
```
f := &File{
    ViewersCanCopyContent: false,
    ForceSendFields: []string{"ViewersCanCopyContent"},
}
```

**Comment by steverippl** [comment]
I'm finding the same problem with updating User in google.golang.org/api/admin/directory/v1. The ChangePasswordAtNextLogin attribute is being left out if set to false, and adding `ForceSendFields:
 []string{"ChangePasswordAtNextLogin"},` doesn't seem to be working. So I don't seem to be able to remove the "change password" flag from the user account if it's previously set.

**Comment by FabioIngrao** [comment]
Try setting the flag: ForceSendFields: []string{"ChangePasswordAtNextLogin
"},

**Comment by steverippl** [comment]
I'm sorry, I don't understand what you mean by "setting the flag" in the context of the struct field? If I add this as a field, as in...

```
user := admin.User{
	ChangePasswordAtNextLogin: false,
	HashFunction:              "MD5",
	Password:                  fmt.Sprintf("%x", md5.Sum([]byte(newPassword))),
	ForceSendFields:           []string{"ChangePasswordAtNextLogin"},
}
```

and then 

```
_, err := srv.Users.Update(email, &user).Do()
```

It doesn't work, the field won't be updated from true to false.

**Comment by FabioIngrao** [comment]
Using the field ForceSendFields as part of the structure File to specify
that a given field should be serialized, worked for my use case.
Another thing that would work, is to modify the struct definition in the
Google Library so that the field is always serialized.

**Comment by jba** [comment]
@steverippl Sorry for the delay in getting back to you on this.

I confirmed that your code sends the right JSON body:
```
{"changePasswordAtNextLogin":false,"hashFunction":"MD5","password":"..."}
```
If it's still not working, I suggest contacting [support for the Admin API](https://developers.google.com/admin-sdk/directory/support), because the problem would be there rather than with this client.
