### ISSUE TITLE
Login using service account without gcloud installed

### ISSUE THREAD

**Issue by MovieStoreGuy** [google/google-api-go-client#230]
I am trying to figure out a way to login authenticate a service account without installing gcloud into a container.

Is such a method possible to do so?

Currently I am setting the `GOOGLE_APPLICATION_CREDENTIALS` to the path were I have the creds stored as json (which is provided from the console) and the API reports back it doesn't have permissions even though it does when I use `gcloud activate-service-account --key-file creds.json` previously, it does.

**Comment by mattwhisenhunt** [comment]
Per our conversation here #250, it looks like you figured this out. Please let me know if you still have any questions.
