### ISSUE TITLE
container-v1alpha1 doesn't seem to be properly generated 

### ISSUE THREAD

**Issue by zudov** [google/google-api-go-client#231]
Hi. I've spotted that following two files are more empty than others:
- [container/v1alpha1/container-api.json](https://github.com/google/google-api-go-client/blob/master/container/v1alpha1/container-api.json)
- [container/v1alpha1/container-gen.go](https://github.com/google/google-api-go-client/blob/master/container/v1alpha1/container-gen.go)

It says of 404s, so maybe there is some issue with fetching that json, maybe wrong name?

**Comment by broady** [comment]
You should probably use container/v1 instead.

Thanks for the report, though, I'll file a bug against that team.

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
