### ISSUE TITLE
Add support for tokeninfo/userinfo

### ISSUE THREAD

**Issue by tlianza** [google/google-api-go-client#236]
The intro docs all emphasize very heavily the fact that we should be validating the oauth token on the server: https://developers.google.com/identity/sign-in/web/backend-auth

> Using one of the Google API Client Libraries (e.g. Java, Node.js, PHP, Python) is the recommended way to validate Google ID tokens in a production environment.

But, I don't see this API included as part of the Go client.

**Comment by jba** [comment]
@zombiezen @broady Do we have a package for this?

**Comment by broady** [comment]
Yep, here:

https://godoc.org/google.golang.org/api/oauth2/v2#Service.Tokeninfo

but also using the plus API:

https://godoc.org/google.golang.org/api/plus/v1#PeopleService.Get

Pass in "me" to get the currently authed user. Sample use:
https://cloud.google.com/go/getting-started/authenticate-users#authenticating_users

**Comment by awreece** [comment]
It looks like the Service.Tokeninfo endpoint is a remote call to https://www.googleapis.com/oauth2/v2/tokeninfo, not a client side validator.

I'd very much prefer to do pure client side validation of the token. Ignoring the performance of the server hop, there might also be practical reasons. 

For example, the google one tap service recommends validating the `hd` field on the jwt returned (https://developers.google.com/identity/one-tap/web/idtoken-auth#verify-the-integrity-of-the-id-token), but it doesn't look like Service.Tokeninfo returns that field.

**Comment by jba** [comment]
These clients are in maintenance mode. We don't plan to address this issue.

@pongad for the next generation of clients.

**Comment by Thearas** [comment]
> It looks like the Service.Tokeninfo endpoint is a remote call to https://www.googleapis.com/oauth2/v2/tokeninfo, not a client side validator.
> 
> I'd very much prefer to do pure client side validation of the token. Ignoring the performance of the server hop, there might also be practical reasons.
> 
> For example, the google one tap service recommends validating the `hd` field on the jwt returned (https://developers.google.com/identity/one-tap/web/idtoken-auth#verify-the-integrity-of-the-id-token), but it doesn't look like Service.Tokeninfo returns that field.

Hi, I meet the same problem, it seems that `https://oauth2.googleapis.com/tokeninfo?id_token=XYZ123` is the right endpoint. See <https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint>.

**Comment by codyoss** [comment]
@Thearas If it is id tokens that you want to validate you may use [idtoken.Validate](https://pkg.go.dev/google.golang.org/api/idtoken#Validate)

**Comment by Thearas** [comment]
Thanks, that's what I want!
