### ISSUE TITLE
Question: API for load balancing

### ISSUE THREAD

**Issue by MrSaints** [google/google-api-go-client#240]
I'm trying to find the appropriate API for Google Cloud Platform's load balancing. i.e. https://console.cloud.google.com/net-services/loadbalancing/

I can't seem to find it, but perhaps it might be termed differently or it might not be available, yet.

**Comment by jba** [comment]
As far as I can tell, there is no API.

**Comment by MrSaints** [comment]
@jba I figured. Do you know if there are any plans to introduce it?

**Comment by jba** [comment]
Load balancing is part of the compute API. Look for ForwardingRules, UrlMaps, TargetHttpsProxies, BackendServices and related resources in [the docs](https://cloud.google.com/compute/docs/reference/latest). Use the [compute/v1](https://github.com/google/google-api-go-client/tree/master/compute/v1) client in this repo.
