### ISSUE TITLE
Authenticating with contents of service account key rather than filepath?

### ISSUE THREAD

**Issue by ljfranklin** [google/google-api-go-client#244]
## Use Case

We're running some tooling in a CI pipeline that passes in the JSON contents of a service account key as an environment variable. We then need a separate step to write the JSON contents into a file before newing up the client with `WithCredentialsFile`. Is it currently possible to pass the JSON contents directly to the go client? If not, would y'all accept a PR to that adds a `WithCredentialsJSON` or similar to take the JSON contents directly?

**Comment by jba** [comment]
We do something similar [here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/internal/testutil/context.go#L64), except we read a file.

Basically, you want
```
conf, err := google.JWTConfigFromJSON(jsonKey, scopes...)
// handle err
ts := conf.TokenSource(ctx)
xxx.NewClient(ctx, option.WithTokenSource(ts))
```
