### ISSUE TITLE
simple calendar example 

### ISSUE THREAD

**Issue by catafest** [google/google-api-go-client#245]
I try to build the calendar example but I got this error:

`C:\Go\bin>go get -u google.golang.org/api/urlshortener/v1

C:\Go\bin\goo>go build -o calendar.go

 _/C_/Go/bin/goo

.\calendar.go:17:2: undefined: registerDemo`

how to fix that ? thank you.

**Comment by mattwhisenhunt** [comment]
Fix that by building with a couple extra source files:
```go build calendar.go main.go debug.go```

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
