### ISSUE TITLE
Please provide a byte array option for firebase.NewApp

### ISSUE THREAD

**Issue by ChrisBartonLC** [google/google-api-go-client#247]
### Describe your environment

  * Operating System version: _____Docker
  * Firebase SDK version: _____Go HEAD of master branch
  * Library version: _____Go HEAD of master branch
  * Firebase Product: _____ (auth, database, storage, etc) auth

### Describe the problem

Please allow the credentials to be provided to "firebase.NewApp" as a byte array in addition to a file via the options. The reason I'm asking is because we store the file encrypted with KMS and would prefer not to write out the decrypted service account to a file and instead keep it in memory.

#### Steps to reproduce:

N/A

#### Relevant Code:

```
	opt := option.WithCredentialsFile("path/to/serviceAccountKey.json")
	client, err := firebase.NewApp(context.Background(), nil, opt)

```

**Comment by ChrisBartonLC** [comment]
See https://github.com/google/google-api-go-client/blob/master/option/option.go#L27

**Comment by ChrisBartonLC** [comment]
For reference see https://github.com/firebase/firebase-admin-go/issues/72

**Comment by michaljemala** [comment]
Hit the same issue. Probably the best resolution will be the ability to pass `io.Reader`, i.e. `func WithCredentialsFile(r io.Reader) ClientOption`, but `[]byte` will do as well!

**Comment by ptone** [comment]
Note this is hardly exclusive to firebase NewApp - the google.golang.org/api/option makes some pretty deep assumptions about working just with filenames instead of io.Reader bytes

**Comment by ChrisBartonLC** [comment]
FYI the work around I posted above doesn't work when minting tokens "auth.CustomTokenWithClaims" so we are back to writing out to a file :(

**Comment by jba** [comment]
See also GoogleCloudPlatform/google-cloud-go#918.

**Comment by jba** [comment]
See https://code-review.googlesource.com/c/google-api-go-client/+/24871 and https://go-review.googlesource.com/c/oauth2/+/99795.

**Comment by jba** [comment]
CLs submitted. Usage:
```
creds, err := google.CredentialsFromJSON(ctx, jsonData, scope1, scope2)
if err != nil { ... }
opt := option.WithCredentials(creds)
```
where `google` is `golang.org/x/oauth2/google` and `option` is `google.golang.org/api/option`.

**Comment by mattwhisenhunt** [comment]
Looks like the bot can't handle cross repo closing.
@michaljemala @ptone @ChrisBartonLC please give us holler (in a comment below) if this fix isn't sufficient for your use cases.

**Comment by ChrisBartonLC** [comment]
Thanks works for us :)
