### ISSUE TITLE
Compute : Adding additional disk during instance creation

### ISSUE THREAD

**Issue by salmanbukhari** [google/google-api-go-client#249]
I am trying to add multiple disks during instance creation. I want to attach Empty disk so I left SourceImage field empty. But I am getting exception

> Got compute.Operation, err: (*compute.Operation)(nil), googleapi: Error 400: Invalid value for field 'resource.disks[1].initializeParams': ''. Source image must be specified., invalid

I am trying something like this

> instance := &compute.Instance{
> 		Name:        instanceName,
> 		Description: "compute sample instance",
> 		MachineType: prefix + "/zones/" + zone + "/machineTypes/n1-standard-1",
> 		Disks: []*compute.AttachedDisk{
> 			{
> 				AutoDelete: true,
> 				Boot:       true,
> 				Type:       "PERSISTENT",
> 				InitializeParams: &compute.AttachedDiskInitializeParams{
> 					DiskName:    "my-root-pd",
> 					SourceImage: imageURL,
> 				},
> 			},
> 			{
> 				AutoDelete: true,
> 				Type:       "PERSISTENT",
> 				InitializeParams: &compute.AttachedDiskInitializeParams{
> 					DiskName:    "instanceex",
> 					DiskSizeGb: 3 ,
> 
> 				},
> 			},
> 		}

**Comment by mattwhisenhunt** [comment]
Hmm, yeah the docs make it seem like you only need one of them to specify sourceImage. I know it is a hassle but have you tried doing it in two steps: creating an instance and then inserting an empty disk?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
