### ISSUE TITLE
Clarification: Listing all members of a project

### ISSUE THREAD

**Issue by MovieStoreGuy** [google/google-api-go-client#250]
I am trying to figure out how I would list all users of a project using this api.

There appears to be no straight forward answer and I would appreciate any help.

**Comment by mattwhisenhunt** [comment]
Which API?

**Comment by MovieStoreGuy** [comment]
I assume it would be cloud resource manager but it is rather hard to tell in my opinion.

**Comment by mattwhisenhunt** [comment]
It looks like you can [list the service accounts](https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/list) assigned to a project thru the API but to get a complete list of permissions you would need to use the [console](https://console.cloud.google.com/iam-admin/iam/project).

It is a bit of a firehouse but https://cloud.google.com/iam/docs/overview explains why you probably want to use service accounts and roles.

**Comment by MovieStoreGuy** [comment]
My intentions is to list all members that are part of a project using a golang api, but from the sounds of it this doesn't possible.

If that is the case, is there plans to provide this feature?

**Comment by mattwhisenhunt** [comment]
That is a question for the API team. My guess would be no. https://github.com/google/google-api-go-client is a library we publish that makes it easy to connect to over 140 Google APIs.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
