### ISSUE TITLE
Fix the broken test

### ISSUE THREAD

**Issue by rakyll** [google/google-api-go-client#251]
```
$ go test google.golang.org/api/...
# google.golang.org/api/transport/bytestream
transport/bytestream/client_test.go:148: Errorf format %s has arg n2 of wrong type int
```

**Comment by mattwhisenhunt** [comment]
I haven't been able to reproduce this error. Is this something a `go get -u` would fix?

I don't know much about go gotten packages. I break my tests all the time when I make edits in $GOPATH. And then I usually give up with git and just delete the repo and get it again.

Maybe grab the commit from $GOPATH/src/google.golang.org/api before you run go get and I can check out that particular version.
