### ISSUE TITLE
pagespeedonline:v4 not available

### ISSUE THREAD

**Issue by orian** [google/google-api-go-client#253]
I've went to the API Discovery service to check if a service is on the list:
https://developers.google.com/discovery/v1/reference/apis/list

It's not. But when I call `getRest` method:
https://developers.google.com/discovery/v1/reference/apis/getRest
and specify api=pagespeedonline, version=v4 it returns the new version.

Not sure what can be done about it.

**Comment by orian** [comment]
As a workaround one may manually download a JSON specification of API and generate it from command line.

**Comment by clarencejychan** [comment]
How are you able to actually generate the clients? I've been running the make file (with and without sudo permissions) which finds the correct discovery document but no .go file is generated.

**Comment by orian** [comment]
`sudo` is necessary. Yes, I've generated a .go file. I didn't call `make`, I've run a generator binary:
https://github.com/google/google-api-go-client/tree/master/google-api-go-generator

I would guess the makefile generates a binary not an api. You have to run this binary.

**Comment by clarencejychan** [comment]
just as a test, i tried something like `sudo -E ./google-api-go-generator -api=youtube:v3` (i added the -E because without it, it complains about `NO GOPATH SET`), after deleting the youtube .go file, yet no code actually generates. I've also tried `sudo -E ./google-api-go-generator -api_json_file=../youtube/v3/youtube-api.json`. Do you mind showing me the command you ran?

**Comment by orian** [comment]
The problem is: some API are not available through `list` endpoint, but you still can download a API spec if you directly fetch the version by calling `getRest`. One must first download not visible api through getRest and later use such json to generate API code.

**Comment by mhupman** [comment]
@orian Would you be willing to publish your version of this library with pagespeedonline v4 support?  That way people could use it in the meantime.

**Comment by mattwhisenhunt** [comment]
If v4 gets published to the discovery doc it will be automatically added to this library.

It looks like it is just [one GET endpoint authenticated with an API key](https://developers.google.com/speed/docs/insights/v4/reference/pagespeedapi/runpagespeed?apix=true#try-it). So this library might almost be too much.

… But to wrap everything up:
```fish
go get google.golang.org/api/...
curl 'https://www.googleapis.com/discovery/v1/apis/pagespeedonline/v4/rest' -H 'Accept: application/json' --compressed > jason
google-api-go-generator -api_json_file jason
rm jason
cd $GOPATH/src/google.golang.org/api/pagespeedonline/v4
#profit
```
