### ISSUE TITLE
Load GOOGLE_APPLICATION_CREDENTIALS without physical file (c#)?

### ISSUE THREAD

**Issue by tazotodua** [google/google-api-go-client#254]
To my surprise, I was unable to find a way to load the credentials file from content on the fly.

If i have that content ( `"type": "service_account",  "project_id"......`) in string variable (i.e. obtained from web-response) , then I want to load that content directly, without storing into ".json" file.

Is there any way to load that directly?

**Comment by bradfitz** [comment]
Are you asking about C# or Go?

In Go, https://godoc.org/golang.org/x/oauth2/google#ConfigFromJSON

For C#, you'd have to ask another project. This is a Go project.
