### ISSUE TITLE
Undocumented visitorId? (YouTube v3 api)

### ISSUE THREAD

**Issue by 0joshuaolson1** [google/google-api-go-client#255]
So this seems like the canonical place to ask:

What is a [visitorId](https://github.com/google/google-api-go-client/blob/afa8e6afb8175363fc9ede3d2978a36a4e4e7c77/youtube/v3/youtube-api.json#L4500)? I can't find any documention from the discovery service, api explorer, or reference.

Also, I don't see a `visitorId` when I make a `youtube.channels.list` request.

**Comment by jba** [comment]
Sorry, this repo is just Go code automatically generated from discovery docs. So we don't know either.

**Comment by 0joshuaolson1** [comment]
Okay. This is under the Google organization. Who would?

**Comment by jba** [comment]
At the bottom of https://developers.google.com/youtube, there are links for the issue tracker and StackOverflow. I'd try those.

**Comment by 0joshuaolson1** [comment]
Thanks. Right, even the discovery team  wouldn't know about all the apis...
