### ISSUE TITLE
Compute: show api request

### ISSUE THREAD

**Issue by bdronneau** [google/google-api-go-client#256]
Hi,

I'm using the client to get snapshots in function of filters
```golang
snapshots, err := computeService.Snapshots.List(projectID).Filter("CreationTimestamp>=2018-03-06T17:56:50).Do()
```

From gcloud cli (working):
```bash
gcloud compute snapshots list --filter="CreationTimestamp<=2018-03-06T17:42:13"
```

I've also try with `createTime` keywork.

Any ideas ?

EDIT : delete AND condition (same behavior)

**Comment by bdronneau** [comment]
After reader and try HTTP API it seem than I can not use `>=`

From [doc](https://cloud.google.com/compute/docs/reference/rest/v1/snapshots/list)
```
The comparison_string must be either eq (equals) or ne (not equals)
```

**Comment by bdronneau** [comment]
@jba you close it because you reach the same conclusion ?

**Comment by jba** [comment]
I'm sorry, I thought you answered your own question. You simply can't filter with anything other than `eq` or `ne`. I assume `gcloud` is using `orderBy="creationTimestamp desc"` and doing its own filtering. I think you will have to do the same.

**Comment by bdronneau** [comment]
Okay no problem, I was just wondering if I understood well the documentation and someone can confirm my suspicion, I think too `gcloud` is doing its own filtering.
Thank anyway.
