### ISSUE TITLE
Build failed for go 1.9+ after Opencensus integration

### ISSUE THREAD

**Issue by bmooso** [google/google-api-go-client#257]
https://travis-ci.org/google/google-api-go-client/jobs/349746868

Importing "cloud.google.com/go/trace" and running "dep ensure -update" now breaks my project with this error:

`vendor/google.golang.org/api/transport/grpc/go18.go:25:45: undefined: ocgrpc.ClientHandler`

**Comment by jba** [comment]
You need to update go.opencensus.io/plugin/ocgrpc to the latest commit.

**Comment by bmooso** [comment]
Updating Gopkg.toml with an override fixed it for me if anyone else runs into this before go.opencensus.io does another release:

```
[[override]]
  name = "go.opencensus.io"
  version = "master"
```

This seems messy but maybe more of a packaging deficiency in Go and not necessarily the wrong way to release the code.

Thanks!
