### ISSUE TITLE
Undefined function referenced: addOCStatsHandler & addOCTransport

### ISSUE THREAD

**Issue by golangdaddy** [google/google-api-go-client#259]
When trying to docker build my repo on remote machine I get this:

vendor/google.golang.org/api/transport/grpc/dial.go:81:13: undefined: addOCStatsHandler
vendor/google.golang.org/api/transport/http/dial.go:54:10: undefined: addOCTransport

Why are those function references in there, when they are breaking the package?

**Comment by mattwhisenhunt** [comment]
It looks to me like the function definitions went in there as part of the [same commit](https://github.com/google/google-api-go-client/commit/a96eae85978352858b50d3d75dadf5f906c2a023) as the calls to them on the lines you mention.

Would you provide a bit more detail about the build failure you are hitting? What docker image? What version of Go?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
