### ISSUE TITLE
how to keep TOKEN be latest version

### ISSUE THREAD

**Issue by kazaff** [google/google-api-go-client#260]
hi there~
I am a newbie for this api project,  Even for golang and google api.

here is my question(as title):
when I use `golang.org/x/oauth2` library to get TOKEN info, it will be save in database(mysql). And when my app run in background for sync the data, it will get the token from db for create client instance, like this:

```go
...
client := googleOauthConfig.Client(c, token)
svc, err := calendar.New(client)
...
```
I know that the library(oauth2 or google-api-go-client) will take care of the “renew token” job, But the problem is how I can get chance to update the corresponding data in db? Or just leave them alone?

Plz show me your code , papa~~😂

**Comment by kazaff** [comment]
Every time, In end of code,  Always need to compare token instance's expiration value? If the value change,  it mean that need to update db?
Do this solution stupid?👿

**Comment by jba** [comment]
> when I use golang.org/x/oauth2 library to get TOKEN info

Can you show the code you're using to do this?

Whatever you store (securely) in your DB shouldn't expire. I think you're storing the access token, which you shouldn't.

Seeing your auth code will help.

**Comment by kazaff** [comment]
@jba thanks for your answer.

I store all part of token, like this:
```go
....
tokenStr, _ := json.Marshal(token)
_, err = db.Exec("INSERT INTO `user_token`(uid,token) VALUE(?,?)", uid.(string), tokenStr)
```
The content include: 
```
{"access_token":"xxxxxx","token_type":"Bearer","refresh_token":"xxxxxxx","expiry":"2018-04-11T05:30:03.1284807-04:00"}
```
As you saw,  Not only `access_token` but also include `refresh_token` and `expiry`.

So what's your opinion?  Waiting for you~~

Thanks again.

**Comment by kazaff** [comment]
emm... I spend some time to check it out, And I found that if choose what I said [in above](https://github.com/google/google-api-go-client/issues/260#issuecomment-380389836), When I want to get the new token instance, I need to use this way:
```go
...
client := googleOauthConfig.Client(c, token)
...
newToken, _ := client.Transport.Source.Token()
```
This method use `Lock` to keep thread safe: 
```go
func (s *reuseTokenSource) Token() (*Token, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.t.Valid() {
		return s.t, nil
	}
	t, err := s.new.Token()
	if err != nil {
		return nil, err
	}
	s.t = t
	return t, nil
}
```
It's to "heavy" for me. So this solution is pretty awkward...

**Comment by hilljgo** [comment]
I too have a question pertaining this issue, is it enough to just pass the `RefreshToken` in the token when creating the client?

 i.e.
```
tok := &oauth2.Token{
   RefreshToken: userRefreshToken,
}

client := oauthConf.Client(oauth2.NoContext, tok)

adminAPI, err := googleAdminDir.New(client)
```

**Comment by kazaff** [comment]
@hilljgo yes, you can.

**Comment by jba** [comment]
@kazaff It sounds like you've found the correct methods: Config.Client or Config.TokenSource.

I don't know why the locking in reuseTokenSource.Token bothers you. That code is in widespread use and there have been no complaints.

**Comment by kazaff** [comment]
@jba Maybe my idea is not quite right, Because in my way that i want to be sure that the token is not expire in every api call, So i need to get the token, Just get the current token, Not to request a new one. As what I said, Maybe I'm wrong~~

Never mind, I have been decided use `Crontab` way.

**Comment by kkesley** [comment]
Hello, I'm trying to do what you're achieving. However I can't seem to be able to use `client.Transport.Source.Token()` because `client.Transport` does not have `Source` as its property. Is `client` a `*http.Client`?

**Comment by jba** [comment]
Did you do the type assertion?
```
transport := client.Transport.(*oauth2.Transport)
```

**Comment by kkesley** [comment]
Ah! I see! Thank you!
