### ISSUE TITLE
How to run scalable microservices with the google api

### ISSUE THREAD

**Issue by wnichols** [google/google-api-go-client#262]
I'm developing microservices for an on premises managed environment.  The actual implementation of that environment is irrelevant except that:
-it runs self contained microservices which may contain functions which access the google api.  It does so by using an embedded copy of the token it recieved at build time.
-it can be scaled from one to n instances
-when its token expires it refreshes it and stores the new token in memory.  It has not access to external storage for the token.

The problem is that when the token is refreshed for the first time, the instance that did it continues while all other instances fail with invalid credentials.  They cannot refresh their tokens because their refresh_token is no longer valid.

My question is:  Is the only way to manage tokens in an environment like this to store them in a shared database such that all instances use exactly the same token?

**Comment by wnichols** [comment]
Ok, no responses immediately.  My solution has been to convert to using service account keys.  This provides me with a non expiring mechanism for accessing the API.  The downside is that the granularity of access for SA keys is not quite as good as OAUTH keys.  For instance the scope of access is either a project, or domain wide, if I understand the doc correctly.  So to control access one must store your objects (sheets in this case) in a project and then dole out access to that to users in the domain.
Be that as it may.. this is an acceptable solution.

**Comment by jba** [comment]
Service account keys&mdash;actually, the JSON that holds the key material and metadata&mdash;is the right thing to go into a persistent store. So sounds like you're on the right track. You should be able to use IAM to give service accounts fairly fine-grained permissions.
