### ISSUE TITLE
Identity Toolkit Create Session Cookie API

### ISSUE THREAD

**Issue by hiranya911** [google/google-api-go-client#263]
Identity Toolkit REST API has a new `createSessionCookie` operation (released a couple of weeks ago). Can this be exposed via https://github.com/google/google-api-go-client/tree/master/identitytoolkit/v3? 

This will enable downstream consumers like Admin SDK to support it.

**Comment by jba** [comment]
That is not exposed in the public discovery doc:
```
> curl https://www.googleapis.com/discovery/v1/apis/identitytoolkit/v3/rest | grep -i cookie
>
```
Once it is exposed, the client should be regenerated within a day.

**Comment by mattwhisenhunt** [comment]
This really will happen automatically so I am going to close this issue.

**Comment by jadekler** [comment]
@fitzoh Firebase team needs to publish it.
