### ISSUE TITLE
Accessing Reseller API with Service Account

### ISSUE THREAD

**Issue by kwiesmueller** [google/google-api-go-client#264]
Hey there!
We are having issues accessing the reseller api using service accounts.
The example with client secrets work well, but we would need to deploy this in k8s (Kubernetes Engine) without the need to refresh the oauth session on a recurring basis (especially doing this once, as it is kinda hard in a docker container).

While there is a lot of documentation on how to do this with python we could not find any way of getting access using a service account.

We tried two accounts, the default compute engine one and one created directly for our use case.
Both got the reseller scope in G Suite.
```
https://www.googleapis.com/auth/apps.order,
https://www.googleapis.com/auth/admin.directory.user,
https://www.googleapis.com/auth/siteverification,
```

We keep getting `"googleapi: Error 403: Authenticated user is not authorized to perform this action., insufficientPermissions"` errors though when using
```go
client, err = google.DefaultClient(ctx, reseller.AppsOrderScope)
if err != nil {
    log.Fatal("creating oauth client failed", zap.Error(err))
}
subs, err := client.Subscriptions.List().Do()
if err != nil {
    log.Fatal("listing subscriptions failed", zap.Error(err))
}
```

I read on a post on StackOverflow, that the Reseller API requires user impersonation but searching on this throughout Google and the oauth2 and client lib repos did not result in a way to do this.
Python does this like described in the End-to-End Tutorial
```python
credentials = ServiceAccountCredentials.from_json_keyfile_name(
    JSON_PRIVATE_KEY_FILE, OAUTH2_SCOPES).create_delegated(RESELLER_ADMIN_USER)
```
but for Go i could not find any documented way of doing this.

I hope for somebody to help us with this as we are being blocked right now.
Cheers,
Kevin

**Comment by jba** [comment]
@zombiezen Can Go's oauth2 stack do this?

**Comment by kwiesmueller** [comment]
FYI: I resolved this after somebody pointed me to a different approach:
```go
const envVar = "GOOGLE_APPLICATION_CREDENTIALS"
	if filename := os.Getenv(envVar); filename != "" {
		serviceAccount, err := ioutil.ReadFile(filename)
		if err != nil {
			log.Fatal("creating oauth client failed", zap.Error(err))
		}
		config, err := google.JWTConfigFromJSON(serviceAccount,
			reseller.AppsOrderScope,
		)

		config.Subject = *impersonationUser // like user@google.com
		client = config.Client(ctx)
	}
```

This was not really shown in any samples I could find on the docs so I would recommend adding this.
If there is a way to add more golang samples to the reseller api reference I would be happy to help with this.

**Comment by safanobu** [comment]
This issue was very helpful.

**Comment by safanobu** [comment]
While this issue is old and already resolved, I would like to point future readers to this official Admin SDK documentation regarding how to implement Workspace Domain-Wide Delegation to a Google Service Account. 

The documentation has a golang example: https://developers.google.com/admin-sdk/directory/v1/guides/delegation#go 

There is also a special mention for the need for admin user impersonation 🎭

**Comment by codyoss** [comment]
That doc might be good for the domain-wide delegation bit. But our impersonate package make the credentials part easier than the example shown I believe: https://pkg.go.dev/google.golang.org/api/impersonate#example-CredentialsTokenSource-AdminUser
