### ISSUE TITLE
[Gmail]Example for send message

### ISSUE THREAD

**Issue by nguyendung17** [google/google-api-go-client#265]
Hi developer team,
I can't find any document related to how to send mail, 
Could you share that document to me?

**Comment by jba** [comment]
I don't know if we have a worked example, but I think you want https://godoc.org/google.golang.org/api/gmail/v1#UsersMessagesService.Send.

**Comment by nguyendung17** [comment]
I did it! <3

func sendMail(srv gmail.Service, from, sender, to, subject, body string) {
	header := make(map[string]string)
	header["From"] = from
	header["To"] = to
	header["Sender"] = fmt.Sprintf("%s <%s>", sender, from)
	header["Content-Type"] = "text/html; charset=\"utf-8\""
	header["Subject"] = subject
	var msg string
	for k, v := range header {
		msg += fmt.Sprintf("%s: %s\r\n", k, v)
	}
	msg += fmt.Sprintf("\n%s\n", body)
	message := gmail.Message{
		Raw: encodeWeb64String([]byte(msg)),
	}
	res, err := srv.Users.Messages.Send(from, &message).Do()
	fmt.Println(toJSON(res))
	fmt.Println(toJSON(err))

}

func encodeWeb64String(b []byte) string {
	s := base64.URLEncoding.EncodeToString(b)
	var i = len(s) - 1
	for s[i] == '=' {
		i--
	}
	return s[0 : i+1]
}


sendMail(*srv, "@gmail.com", "Dung Nguyen",
		"@gmail.com", "subject", "<h1 style='color:red'>body</h1>")
