### ISSUE TITLE
question: how to add a tag to an existing image?

### ISSUE THREAD

**Issue by stevenbarragan** [google/google-api-go-client#266]
Is there a way to do `gcloud beta container images add-tag` through the go api?

**Comment by bradfitz** [comment]
Almost certainly, because `gcloud` just uses the same APIs.

**Comment by jba** [comment]
Google Container Registry doesn't provide an API for managing images, so there is no Go client in this repo. `gcloud` uses [this Python client](https://github.com/google/containerregistry) for the [Docker Registry API](https://docs.docker.com/registry/spec/api/). It implements `add-tag` by doing a push.

**Comment by stevenbarragan** [comment]
Interesting, thanks @jba
