### ISSUE TITLE
undefined: google.CredentialsFromJSON

### ISSUE THREAD

**Issue by u007** [google/google-api-go-client#267]
hi,

im getting 
vendor/google.golang.org/api/internal/creds.go:36:10: undefined: google.CredentialsFromJSON

ive go get -u golang.org/x/oauth2/google, but with this error

sorry realize go get works, but dep ensure --add seems not get a version that does not contains go19.go

**Comment by bradfitz** [comment]
google.CredentialsFromJSON definitely exists, and you've found it when you run "go get", so this 
might be a better question for a dep users mailing list or the dep bug tracker.
