### ISSUE TITLE
how can authenticate with a backend server

### ISSUE THREAD

**Issue by alex023** [google/google-api-go-client#268]
According to the description of this web page [Authenticate with a backend server] (https://developers.google.com/identity/sign-in/web/backend-auth), I want to implement it on the server using go. 
But I'm not sure if I should use the `oauth2-gen.go` . I am confused it's name of  package and  function, it's so different from the other languages of the sample.
hope for anwser. thanks!

**Comment by jba** [comment]
Perhaps you want https://godoc.org/google.golang.org/api/oauth2/v2#TokeninfoCall?

@zombiezen, any other suggestions?

**Comment by zombiezen** [comment]
Tokeninfo would work, as I believe would using something like [square/go-jose](https://github.com/square/go-jose), which can verify and parse JWTs.

**Comment by alex023** [comment]
Thks

**Comment by mattwhisenhunt** [comment]
Seems like this is answered. Holler if you need anything else.
