### ISSUE TITLE
omitempty for boolean fields causing not updated records

### ISSUE THREAD

**Issue by andrewkavalionak** [google/google-api-go-client#271]
The `IdentitytoolkitRelyingpartySetAccountInfoRequest` has `EmailVerified` field which has `json:"emailVerified,omitempty"` tag, the value will be not serialised when passing `false` so this causes record not being updated.

The `omitempty` tag should be removed from boolean fields.

**Comment by bradfitz** [comment]
But then you have the opposite problem.

What you're actually looking for is ForceSendFields.

**Comment by andrewkavalionak** [comment]
@bradfitz you are right. thank you!
