### ISSUE TITLE
Test with api/compute

### ISSUE THREAD

**Issue by bdronneau** [google/google-api-go-client#276]
Hi,

I've write cli program to generate reports from my GCP plateform.
I would like to do some tests (without call to GCP) on my functions but I don't know how to simulate the [client](https://github.com/google/google-api-go-client/tree/master/compute/v1) (`compute.New(client)`). 
If someone have examples.

Thank

**Comment by mattwhisenhunt** [comment]
Also if you are working exclusively with Google Cloud Platform APIs please check out https://github.com/GoogleCloudPlatform/google-cloud-go . Give us holler or add a comment if you have any more questions.

**Comment by bdronneau** [comment]
Hi thank for your answer. I'll give a try to simulate the transport.
