### ISSUE TITLE
Unable to fetch bucket contents

### ISSUE THREAD

**Issue by akskap** [google/google-api-go-client#277]
Requirement : Want to figure out bucket contents older than a specific date

Tried the following code (authenticated with a service-accounts.json file)

```
projectId := os.Getenv(constants.ENV_GCP_PROJECT_ID)
resp, err := computeService.BackendBuckets.Get(projectId, containerName).Context(ctx).Do()
if err != nil {
    fmt.Println("Error ", err)
}
```
It throws an error which says:
```
Error  googleapi: Error 404: The resource 'projects/<project_name>/global/backendBuckets/<bucket_name>' was not found, notFound
```
I can see the bucket listed on Google Cloud Console

Doubts:

a) Am I using the correct API for fetching all information stored inside a container/bucket ? (computeService.BackendBuckets.Get....)

b) Only difference I see in browser console, is that buckets location shows as regional and the error I am getting the client-library mentions ..../global/....
Can this be a reason for this error ? If yes, can you please suggest how to pass the regional flag in the API ?

**Comment by mattwhisenhunt** [comment]
For new code I suggest you check out the GCP clients: https://github.com/GoogleCloudPlatform/google-cloud-go#cloud-storage-

If you are sticking with this library I think you are looking for the [storage package](https://godoc.org/google.golang.org/api/storage/v1) not compute.

**Comment by jba** [comment]
I'm not really familiar with this feature, but from reading [this doc page](https://cloud.google.com/compute/docs/load-balancing/http/adding-a-backend-bucket-to-content-based-load-balancing) it appears that the backend bucket name is not the same as the name of the bucket in cloud storage. 

You're using the right API, but check the name of the backend bucket in your load balancer configuration. 

Also, these are definitely Google Cloud Storage buckets, and not related to "containers" as that word is usually used these days.
