### ISSUE TITLE
cannot upload custom metric

### ISSUE THREAD

**Issue by nmylarappa** [google/google-api-go-client#289]
I have added a new metric and trying to upload double click conversions. I am running it this below issue. I have setup this custom metric in DCM as well.

400
 
- Show headers -
  
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "requestValidation",
    "message": "The request was not valid. Details: [0x00000116: Custom metric 'Banking Account Opens' is not found for conversion index=0

**Comment by mattwhisenhunt** [comment]
What API and action produced this error?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
