### ISSUE TITLE
Support batch requests

### ISSUE THREAD

**Issue by gmlewis** [google/google-api-go-client#29]
**kevlar@google.com** on 16 Apr 2013 at 3:50:

```
For a description of how batching works, see e.g.
https://developers.google.com/coordinate/v1/batch

It seems to be something that works on many if not all APIs.

I haven't decided exactly what the best way to handle it would be, but it seems 
like one might be able to construct an http.Client which transparently did 
batching.  When a Dial is done on the transport, it returns a conn whose other 
end is actually a local piece of code reading the HTTP request and adding it to 
the batch; then when the pseudo-Client's "Release" method (or similar) is 
called, all queued requests are assembled, sent, and then distributed back out 
to the waiting net.Conns.  Magic :).

The less magical way would be to generate additional APIs along the lines of

func (WhateverCall) AddTo(b Batch) (*Result, *error) { ... }

and then the Batch would have a Do which assembled the requests, decoded the 
responses into the pointers, etc.  I'm not sure how I feel about the 
pointer-to-error, though.

The up-shot of the first is that you can e.g. request a list of IDs, spin up a 
goroutine for each, and then every 100ms or so release the batch queries until 
all of the goroutines are done doing their work.  They would see it as a 
sequential request.  The up-shot of the second is that the batching is explicit 
in the code, but it seems a lot harder to use.

I might play around with this at some point if you think it's a good idea.
```

**Comment by odeke-em** [comment]
Isn't this an outdated issue since we now have ExportLinks map[string]string
https://github.com/google/google-api-go-client/blob/master/drive/v2/drive-gen.go#L815
and
https://github.com/google/google-api-go-client/blob/master/drive/v2/drive-gen.go#L1284
which seem like the recommendations from the issue.

**Comment by odeke-em** [comment]
Got fixed by commit https://github.com/google/google-api-go-client/commit/532c20d4b6728c1f97cdd9e54a94f0fa4a85460e

**Comment by gmlewis** [comment]
PLEASE hold off on commenting on any issues until I get them all imported from code.google.com.
Thank you!

**Comment by gmlewis** [comment]
Successfully auto-migrated from code.google.com:
https://code.google.com/p/google-api-go-client/issues/detail?id=29

**Comment by gmlewis** [comment]
This sounds like a cool feature to support.  It will take more thought on how to add this without breaking existing clients.  Leaving issue open.

**Comment by jfcote87** [comment]
http://godoc.org/github.com/jfcote87/google-api-go-client/batch

I'm not thrilled with it, but I do use it in production.  No changes to the existing clients are needed.

**Comment by gmlewis** [comment]
Thanks for the link, @jfcote87 !

**Comment by josephspurrier** [comment]
@jfcote87 Jim, you are a trailblazer my friend. Works like a charm! Way better than using goroutines to download message from the Gmail API.

**Comment by porjo** [comment]
+1

**Comment by jba** [comment]
These clients are in maintenance mode. We won't be adding new features.

@pongad for the next generation of clients.
