### ISSUE TITLE
Add instanceGroupManagers.update

### ISSUE THREAD

**Issue by nfisher** [google/google-api-go-client#291]
It appears not all of the API end-points appear in the generated libraries. In particular when I run grep on the file below it appears that `instanceGroupManagers.update` is absent.
https://raw.githubusercontent.com/google/google-api-go-client/master/compute/v1/compute-gen.go

```
grep -i compute.instanceGroupManagers compute-gen.go | grep "method id"
// method id "compute.instanceGroupManagers.abandonInstances":
// method id "compute.instanceGroupManagers.aggregatedList":
// method id "compute.instanceGroupManagers.delete":
// method id "compute.instanceGroupManagers.deleteInstances":
// method id "compute.instanceGroupManagers.get":
// method id "compute.instanceGroupManagers.insert":
// method id "compute.instanceGroupManagers.list":
// method id "compute.instanceGroupManagers.listManagedInstances":
// method id "compute.instanceGroupManagers.recreateInstances":
// method id "compute.instanceGroupManagers.resize":
// method id "compute.instanceGroupManagers.setInstanceTemplate":
// method id "compute.instanceGroupManagers.setTargetPools":
```

https://cloud.google.com/compute/docs/reference/rest/beta/instanceGroupManagers/update

Understand the API is largely generated what's required if anything to add that end-point?

**Comment by jba** [comment]
It needs to appear in the discovery document at https://www.googleapis.com/discovery/v1/apis/compute/v1/rest. I don't know why it's in the docs but not there. I'll see if I can find out.

**Comment by nfisher** [comment]
This is the rest signature which has a beta segment instead of v1. Could that be part of it?

`https://www.googleapis.com/compute/beta/projects/{project}/zones/{zone}/instanceGroupManagers/{resourceId}`

**Comment by jba** [comment]
That's it! See the client under compute/v0.beta.

**Comment by nfisher** [comment]
Ah yea found `instanceGroupManagers.update` under here;
https://www.googleapis.com/discovery/v1/apis/compute/beta/rest

Is there a long cycle to add that and release or should I fork and generate the client myself?

**Comment by nfisher** [comment]
Apologies closing issue found it in the package structure was pruned in my vendor folder. :/
