### ISSUE TITLE
Support for Standard Query Parameters (fields, quotaUser, userIp, etc) in Google APIs

### ISSUE THREAD

**Issue by gmlewis** [google/google-api-go-client#40]
**shazow** on 5 Sep 2013 at 4:40:

```
Most (if not all) Google API's support standard query parameters, such as ones 
documented here:
https://developers.google.com/discovery/v1/parameters
https://developers.google.com/drive/query-parameters
https://developers.google.com/analytics/devguides/reporting/realtime/v3/paramete
rs
Etc.

There doesn't seem to be a way to set these using the google-api-go-client 
library.

Would be great if there was native support for these fields. Perhaps it would 
make sense letting the user set arbitrary fields to the opt_ field map, for 
future workarounds to such limitations?

Related bugs:
#5 https://code.google.com/p/google-api-go-client/issues/detail?id=5
#38 https://code.google.com/p/google-api-go-client/issues/detail?id=38

I would consider this bug to be a superset of the other two.

Thanks!
```

**Comment by gmlewis** [comment]
Successfully auto-migrated from code.google.com:
https://code.google.com/p/google-api-go-client/issues/detail?id=40

**Comment by gmlewis** [comment]
`fields` has been implemented by https://github.com/google/google-api-go-client/commit/41bebb44517bb8dc703677d642e4ee6dc79a6ff4
`prettyPrint` doesn't seem terribly useful for an auto-generated client library.
I don't think `callback` would be useful to an auto-generated client library either, but I could be wrong.

I'll leave this open for implementing `quotaUser` and `userIp`.

**Comment by dsymonds** [comment]
`quotaUser` and `userIp` were added in dc6d235 (Dec 2015) by @mcgreevy.
