### ISSUE TITLE
feature: add BasePath so you can tune the API's basepath

### ISSUE THREAD

**Issue by gmlewis** [google/google-api-go-client#48]
**brandon.philips@coreos.com** on 21 Nov 2013 at 8:29:

```
feature: add BasePath so you can tune the API's basepath

Useful if you are using something like https://github.com/rwl/endpoints

https://code.google.com/r/brandon-tunable-basepath/source/detail?r=1706a3e83ed9f
5a25a221605965fad5167315feb

```

**Comment by gmlewis** [comment]
Successfully auto-migrated from code.google.com:
https://code.google.com/p/google-api-go-client/issues/detail?id=48

**Comment by gmlewis** [comment]
Fixed by https://github.com/google/google-api-go-client/commit/3a988841aa2aadf4284c63e87d84d644d509cf68
Closing.

**Comment by philips** [comment]
Thanks!
