### ISSUE TITLE
Where new issues should be reported?

### ISSUE THREAD

**Issue by gmlewis** [google/google-api-go-client#73]
**kuangche** on 22 Mar 2015 at 5:38:

```
This project was moved to https://github.com/google/google-api-go-client
But the issues are not moved to and not open to create new issues there.

Where new issues should be reported?
```

**Comment by odeke-em** [comment]
I think this can now be closed since all the issues were migrated and reporting one is now possible here on Github.

**Comment by gmlewis** [comment]
Yes, thanks, @odeke-em.  In fact, I plan on doing a full issue scrub soon for this repository.

**Comment by odeke-em** [comment]
Cool, I figured you'd do that ;)

**Comment by gmlewis** [comment]
Successfully auto-migrated from code.google.com:
https://code.google.com/p/google-api-go-client/issues/detail?id=73
