### ISSUE TITLE
adsense, multiple metrics and dimensions are not supported

### ISSUE THREAD

**Issue by gmlewis** [google/google-api-go-client#74]
**luca.looz92** on 29 Mar 2015 at 8:38:

```
The adsense client doesn't support multiple metrics and dimensions when 
generating a report 
(https://github.com/google/google-api-go-client/blob/master/adsense/v1.4/adsense
-gen.go#L2335)

Methods "Dimension" and "Metric" accepts a single value string instead of an 
expected []string slice 
(https://github.com/google/google-api-go-client/blob/master/adsense/v1.4/adsense
-gen.go#L2353, 
https://github.com/google/google-api-go-client/blob/master/adsense/v1.4/adsense-
gen.go#L2382).
Those accepted values currently are considered a single query param 
(https://github.com/google/google-api-go-client/blob/master/adsense/v1.4/adsense
-gen.go#L2430)

AdSense Management API supports multiple metrics and dimensions 
(https://developers.google.com/adsense/management/metrics-dimensions), on API 
Explorer 
(https://developers.google.com/apis-explorer/#p/adsense/v1.4/adsense.accounts.re
ports.generate) you can see that there is an "add more" button to add multiple 
metrics and dimension, those are appended as multiple query parameters: 
"&dimension=AD_UNIT_ID&dimension=AD_UNIT_NAME&metric=AD_REQUESTS&metric=EARNINGS
"

Just to get it working i have forked the repository and committed a simple fix 
(https://github.com/Idhor/google-api-go-client/commit/9e09a005b99267d895e0bf82c8
66af73ae3b0028)
```

**Comment by gmlewis** [comment]
Successfully auto-migrated from code.google.com:
https://code.google.com/p/google-api-go-client/issues/detail?id=74

**Comment by gmlewis** [comment]
Working on fix.

**Comment by gmlewis** [comment]
@bradfitz - we have a couple ways that I can think of for supporting optional repeated fields:

* break the API and change the parameter from a string to a slice of strings (e.g. `Dimension(dimension string)` to `Dimension(dimension []string)`)

* support passing either a single string or slice of strings by passing in an `interface{}`, and not break any existing users of the API (e.g. `Dimension(dimension interface{})`

I'm thinking that the first option is probably the lesser of two evils... because it really should be a slice of strings... and if people are already using it, they may actually appreciate the change and the fix.  The second option is just plain ugly and obfuscates what type should really be passed.

Or is there a better option that I haven't thought of?

**Comment by bradfitz** [comment]
What's the JSON discovery file look like for these fields?

**Comment by gmlewis** [comment]
```json
        "dimension": {
         "type": "string",
         "description": "Dimensions to base the report on.",
         "pattern": "[a-zA-Z_]+",
         "repeated": true,
         "location": "query"
        }
```

**Comment by jba** [comment]
These clients are in maintenance mode. We don't plan to address this issue.

@pongad for the next generation of clients.
