### ISSUE TITLE
enums should be supported

### ISSUE THREAD

**Issue by gmlewis** [google/google-api-go-client#77]
In logging:v1beta3, `enum`s are not yet supported:

```json
  "LogEntryMetadata": {
   "id": "LogEntryMetadata",
   "type": "object",
   "description": "Additional data that is associated with a log entry, set by the service creating the log entry.",
   "properties": {
    "timestamp": {
     "type": "string",
     "description": "The time the event described by the log entry occurred. Timestamps must be later than January 1, 1970."
    },
    "severity": {
     "type": "string",
     "description": "The severity of the log entry.",
     "enum": [
      "DEFAULT",
      "DEBUG",
      "INFO",
      "NOTICE",
      "WARNING",
      "ERROR",
      "CRITICAL",
      "ALERT",
      "EMERGENCY"
     ]
    },
```

turns into:
```go
type LogEntryMetadata struct {
...
        // Severity: The severity of the log entry.
        Severity string `json:"severity,omitempty"`
```

Please note that as a temporary workaround, you can manually set the Severity string to `"DEFAULT"`, `"DEBUG"`, etc. until enums are supported (or fixed) by google-api-go-client.

**Comment by gmlewis** [comment]
This is a duplicate of issue #81.
Closing.

**Comment by gmlewis** [comment]
@bradfitz - Do we want to do more with enums other than listing all the possible values in the comments like are done in Issue #81 ?
I closed this one, but then realized that maybe we want to change the type to a specific type like:

type SeverityEnum string

and then literally enumerate just the possible values.
Thoughts?

**Comment by bradfitz** [comment]
Perhaps. Doesn't seem critical, though. The docs were a huge win but adding more types might just pollute things more than they add.

**Comment by gmlewis** [comment]
OK, I agree.  I'm going to close this one.  Thanks, Brad!
