### ISSUE TITLE
inconsistent package names

### ISSUE THREAD

**Issue by bradfitz** [google/google-api-go-client#78]
I just noticed we have a few APIs where the version isn't in the normal "vNNN" form:

```
ante:api $ find -type d | grep _v
./admin/directory_v1
./admin/reports_v1
./admin/email_migration_v2
ante:api $ head admin/directory_v1/admin-gen.go 
// Package admin provides access to the Admin Directory API.
//
// See https://developers.google.com/admin-sdk/directory/
//
// Usage example:
//
//   import "google.golang.org/api/admin/directory_v1"
//   ...
//   adminService, err := admin.New(oauthHttpClient)
package admin
```

That means you'd import `import "google.golang.org/api/admin/directory_v1"` but refer to it as `admin`, which is weird.

Further, https://code-review.googlesource.com/#/c/2370/ proposes adding `import "google.golang.org/api/computeaccounts/alpha"` imported as `computeaccounts`, which is even weirder, since it doesn't even have "v" in the final path component.

We should remap these to something cleaner.  Like `google.golang.org/api/admin/directory/v1` and `google.golang.org/api/computeaccounts/v0.alpha` perhaps.

/cc @gmlewis

**Comment by gmlewis** [comment]
It looks like v0.alpha was handled in https://github.com/google/google-api-go-client/commit/f99e8ddfd771d4540a11c84a0ca65aa1e50e03f6
but we still have weird names in admin which has `directory_v1`, `email_migration_v2` and `reports_v1`.
