### ISSUE TITLE
When trying to delete a bucket with objects in it, the API call suppresses the error

### ISSUE THREAD

**Issue by dhilton** [google/google-api-go-client#84]
To replicate:

```golang

// delete a bucket called "i-have-objects"
err := service.Buckets.Delete("i-have-objects").Do()

if err == nil {
   fmt.Printf("Bucket deleted")
} else {
   fmt.Printf("Bucket not deleted")
}

```

In that scenario, I seem to get a value of <nil> when printing err, however the JSON API returned 409 HTTP access code. 

I'm testing this against the EU location and the latest version of the library on google.golang.org 

Is this the expected behaviour?

**Comment by gmlewis** [comment]
You "get a value of when printing err"?  What does that mean?
Are you saying that you get `nil` when the bucket is not deleted?

**Comment by dhilton** [comment]
When I try to delete a bucket that contains objects, the delete apparently tells me that it has completed the action correctly when in fact it hasn't.

When I print the err I get "<nil>" however the named bucket is not deleted and the API (when I query it via the API explorer) gives me a 409:

```
409 Conflict
 
- Hide headers -
 
cache-control:  private, max-age=0
content-encoding:  gzip
content-length:  151
content-type:  application/json; charset=UTF-8
date:  Fri, 22 May 2015 10:41:55 GMT
expires:  Fri, 22 May 2015 10:41:55 GMT
server:  GSE
vary:  Origin, X-Origin
 
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "conflict",
    "message": "The bucket you tried to delete was not empty."
   }
  ],
  "code": 409,
  "message": "The bucket you tried to delete was not empty."
 }
}
```

I would expect err to be non-nil and give me some sort of readable error message?

**Comment by gmlewis** [comment]
OK, I will investigate when I have time.  Meanwhile, have you tried the Go veneer client library?
https://github.com/GoogleCloudPlatform/gcloud-golang
I'm surprised by this bug report because the Go veneer client library uses this auto-generated library and it correctly reports when a bucket can not be deleted... but I will look into it.

**Comment by gmlewis** [comment]
Here is a complete example, and it seems to me to be "Working as intended".  Am I missing something?

```
go run bug.go --bucket my-bucket
2015/05/22 09:16:27 Bucket not deleted: googleapi: Error 409: The bucket you tried to delete was not empty., conflict
exit status 1
```

and now the code:

```go
package main

import (
	"flag"
	"fmt"
	"log"
	"os"

	"golang.org/x/net/context"
	"golang.org/x/oauth2/google"
	storage "google.golang.org/api/storage/v1"
)

var (
	bucket = flag.String("bucket", "", "Name of bucket to delete")
)

func main() {
	flag.Parse()
	if *bucket == "" {
		fmt.Fprintln(os.Stderr, "Usage: %s --bucket bucket-name")
		os.Exit(1)
	}

	client, err := google.DefaultClient(context.Background(), storage.DevstorageReadWriteScope)
	if err != nil {
		log.Fatalf("Unable to create default client: %v", err)
	}

	service, err := storage.New(client)
	if err != nil {
		log.Fatalf("Unable to create Storage service: %v", err)
	}

	if err := service.Buckets.Delete(*bucket).Do(); err != nil {
		log.Fatalf("Bucket not deleted: %v", err)
	}

	fmt.Printf("Bucket deleted.")
}
```

**Comment by dhilton** [comment]
Hrm - The only difference in your code is your dereferencing the bucket when passing to the Delete function. Will look again at my code further up the stack - thanks for your help.
