### ISSUE TITLE
Please include a snippet to use the Application Default Credentials

### ISSUE THREAD

**Issue by vsubramani** [google/google-api-go-client#89]
adg@ had added support for the Application Default Credentials feature. Please add usage instructions in this repro's readme file to help developers who want to use this feature when consuming Google Cloud APIs.

Here are some ruby and node example documentation for reference. 
https://github.com/google/google-auth-library-ruby
https://github.com/google/google-auth-library-nodejs

**Comment by matyuss** [comment]
Matyuss

**Comment by evandbrown** [comment]
I've looked around but can't see where @adg added Application Default Credentials? @vsubramani, can you point to that?

**Comment by gmlewis** [comment]
I think he is referring to this: https://github.com/golang/oauth2/blob/master/google/default.go
