### ISSUE TITLE
Recent Go commit causes admin.MembersListCall (and likely others) to intermittently return EOF errors 

### ISSUE THREAD

**Issue by mjard** [google/google-api-go-client#90]
Go commit golang/go@0cf48b4d919e5137ec03f1bf230fbd8720873151 recently added streaming features to JSON package in the standard library. Unfortunately it seems to have also changed the way EOF errors were handled and they are now being pushed to the client. Attempting to access elements in result ends with a panic, so it seems the json parsing is not completing.

**Comment by gmlewis** [comment]
Link:
https://github.com/golang/go/commit/0cf48b4d919e5137ec03f1bf230fbd8720873151

**Comment by mjard** [comment]
Looks like golang/go#11893 is tracking this regression.

**Comment by mjard** [comment]
Russ fixed with commit golang/go@22936858b9b263f69707246a7527115bbd7d0b95, think this can be closed.
