### ISSUE TITLE
Taskqueue task delete fails unless project-name prefixed with "s~"

### ISSUE THREAD

**Issue by bthomson** [google/google-api-go-client#92]
This is for: "google.golang.org/api/taskqueue/v1beta2"

Deleting a task fails unless project-name is prefixed with "s~". Lease() is not affected, which makes it confusing to figure out what's gone wrong (one would expect the same project name could be used for both calls)

This is not a bug in the Go code because Python is also affected. However, I thought you guys might be able to figure out how to get it fixed upstream?

Here's the Python issue:

https://code.google.com/p/google-api-python-client/issues/detail?id=308

Here are some code snippets:

```
ts, err := svc.Lease("myappidhere", "myQueueName", 1, 100).Do()
err := svc.Delete("s~myappidhere", "myQueueName", "myTaskId").Do()
```

**Comment by gmlewis** [comment]
Thanks for the report.  I'll contact the TaskQueue API team and report back with any findings.

**Comment by gmlewis** [comment]
I have found out from the TaskQueue that this is a known issue that will not be fixed because their REST API is fixed.
Sorry about that.

**Comment by drichardson** [comment]
When deleting, should the project name always be prefixed with "s~"? Or should the project name be parsed out of the queueName field that appears in the lease JSON response, which has the format `projects/s~<PROJECT_NAME>/taskqueues/<QUEUE_NAME>`?

**Comment by drichardson** [comment]
This is what I'm doing now and it's working for me:

```
var ErrInvalidArg = errors.New("Invalid Argument")

func parseQueueName(task *taskqueue.Task) (projectName, queueName string, err error) {
    // Parse out the queue name and project name that appear in the task's queuename field.
    // They are prefixed (in my experience, with s~) and if you don't use the prefixed
    // names the task queue delete will fail with an invalid project error.
    // Issue: https://code.google.com/p/googleappengine/issues/detail?id=10199
    // task.QueueName has the format project/<prefixed_project_name>/taskqueue/<task_queue_name>
    parts := strings.Split(task.QueueName, "/")
    if len(parts) != 4 {
        err = ErrInvalidArg
        return
    }

    projectName = parts[1]
    queueName = parts[3]
    return
}
````

**Comment by gmlewis** [comment]
That seems reasonable.  Yes, it should be parsed... it is not a constant prefix.
