### ISSUE TITLE
Document error return types

### ISSUE THREAD

**Issue by odeke-em** [google/google-api-go-client#93]
I have an application based off drive/v2 that needs to perform some sort of retry mechanism whenever I get certain temporary errors.
Currently every error returned by the drive/v2 API is directly an 'instance' of the builtin error interface. This means that the returned `Code` and `Body` of the actual type `googleapi.Error` can't be directly accessed unless I perform some type assertions e.g

``` go
func translateError(e error) (msg string, retryable bool) {
    gErr, ok := e.(*googleapi.Error)
    if !ok {
        msg = e.Error()
        return
    }

    msg = gErr.Body
    if msg == "" {
        msg = gErr.Error()
    }

    if gErr.Code >= 500 && gErr.Code <= 599 {
        retryable = true
    } else {
        switch gErr.Code {
        case 401, 403:
            retryable = true
        }
    }

    return
}
```

 I wanted to ask if is reasonable to change the signatures of *.Do() (.., error) to *.Do() (..., googleapi.Error) since it still conforms to the builtin error.

**Comment by bradfitz** [comment]
That's against Go style and also breaks compatibility and introduces bugs like http://golang.org/doc/faq#nil_error

Instead, we can just document that all errors are of type X (if that is already the case), like the os package does with PathError and LinkError.

/cc @gmlewis

**Comment by odeke-em** [comment]
Ah I see, thank you for that information @bradfitz -- I've learnt something new this morning. For sure documenting them sounds like a plan.

**Comment by gmlewis** [comment]
Brad, I've gone through the code, and the errors returned are not always of type *googleapi.Error.
(For example, sometimes they are errors returned by json.Decode.)

Should I force them to always be of type *googleapi.Error, or should I just document that they are `sometimes of type *googleapi.Error` and need to be tested as in the example code above?

And if I forced them to always be of type *googleapi.Error, what should be the return code for the other errors... maybe 400 `StatusBadRequest` or 500 `StatusInternalServerError`?

**Comment by jba** [comment]
I'll add something to GettingStarted.md about this.
