### ISSUE TITLE
AdWords API is missing

### ISSUE THREAD

**Issue by pwaller** [google/google-api-go-client#95]
I'm interested in using the [`TrafficEstimatorService`](https://developers.google.com/adwords/api/docs/reference/v201506/TrafficEstimatorService), but it is unclear how/whether I can achieve that with `google-api-go-client`, either now or in the future.

Is there something easy I can do to generate it?

**Comment by gmlewis** [comment]
Please try this:
```
$ make generator
$ google-api-go-generator -cache=false -publiconly=false -api adwords:v201506
```

**Comment by pwaller** [comment]
It seems that all this generated was this:

```
type Service struct {
    BasePath  string // API endpoint base URL
    UserAgent string // optional additional User-Agent fragment
    // contains filtered or unexported fields
}

func New(client *http.Client) (*Service, error)
```

```
$ cat adwords-api.json 
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "Not Found"
   }
  ],
  "code": 404,
  "message": "Not Found"
 }
}
```

**Comment by gmlewis** [comment]
Whups, for me too.  Investigating.

**Comment by gmlewis** [comment]
Unfortunately, the AdWords API is not available as a REST API.
Its API is provided as a set of web services via SOAP.
Closing issue, as it is not possible to access the AdWords API via google-api-go-client.

**Comment by Robvio** [comment]
> Closing issue, as it is not possible to access the AdWords API via google-api-go-client.

Is there any other offering from google that allows you to access the google adwords api from golang?
