### ISSUE TITLE
Go App Imports not found

### ISSUE THREAD

**Issue by SpaceNav** [google/google-api-go-client#97]
I found the fix to the issue below:

After a ton of digging, I had to run the "sudo goapp get google.golang.org/api/compute/v1" command and this seems to have fixed it.  (All the documentation says "go" vs. "goapp" which took me a while to find)

I do not understand why I had to do this, as this was working before.  I did see that the repo was moved, and that would do it, but, I thought I saw something that said the code was going to stay in the original location.  (But I think I have the correct location now, so that is very positive :))

----------------------------------------------------------

I  am getting import errors in my AppEngine Go Application when  I try to deploy it using the following command:

./appcfg.py --noauth_local_webserver update /xxxx/xxxxxx/AppEngineCode/src/xxxxxx/ 

Compile failed:
2015/08/25 20:52:40 go-app-builder: build timing: 1×6g (35ms total), 0×gopack (0 total), 0×6l (0 total)
2015/08/25 20:52:40 go-app-builder: failed running 6g: exit status 1
mailbox.go:13: can't find import: "golang.org/x/oauth2"
--- end server output ---
03:52 AM Rolling back the update.

This worked last time I tried to do it, which was a few months ago. I am attempting to get this Go Application deployed to an AppEngine so that I can then start compute engines from the Go Application.

I am clearly missing some setup step, or something because non of the golang.org imports seem to be found.

import (
	"fmt"
	"net/http"
	"net/mail"

	//"golang.org/x/build/buildlet"
	//"golang.org/x/build/dashboard"
	//"golang.org/x/build/gerrit"
	//"golang.org/x/build/internal/lru"
	//"golang.org/x/net/context"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
	compute "google.golang.org/api/compute/v1"

**Comment by gmlewis** [comment]
What happens if you `go get golang.org/x/oauth2`?

**Comment by SpaceNav** [comment]
Then it cant find this import.

mailbox.go:21: can't find import: "golang.org/x/oauth2"

Thanks
Dave

------ Original Message ------

**Comment by gmlewis** [comment]
Is your `$GOPATH` set up properly?
```bash
$ mkdir -p $HOME/go/src
$ export GOPATH=$HOME/go
$ go get golang.org/x/oauth2
```
How are you running the compile command?

**Comment by SpaceNav** [comment]
Got it...
Thanks everyone.

I had to use the goapp command to get the correct packages installed:

  goapp get golang.org/x/oauth2

Thanks again!
Dave
------ Original Message ------
