### ISSUE TITLE
oauth2.Transport not found?

### ISSUE THREAD

**Issue by SpaceNav** [google/google-api-go-client#98]
Since I have pulled in the new repository, I have been looking for what I need to import (or install) to get the Transport object available to my Go program.  Imports and snippet below.

import (
	"fmt"
	"net/http"
	"net/mail"
	"appengine"
	newappengine  "appengine"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/oauth2/v1"
)

	"appengine/urlfetch"client := &http.Client{
		Transport: &oauth2.Transport{
			Source: google.AppEngineTokenSource(ctx, compute.ComputeScope),
			Base:   &urlfetch.Transport{Context: ctx},
		},

This is frustrating because either I am not seeing certain things in the documentation, or it has not been updated?  I am probably missing something simple...
Did it used to be in here?    "golang.org/x/oauth2/google"

This seems to be the only import that I don't  have and cannot find from the new repository... 

Thanks
Dave

**Comment by bradfitz** [comment]
You never imported oauth2.

It's still there: http://godoc.org/golang.org/x/oauth2#Transport

**Comment by bradfitz** [comment]
Oh, you imported "google.golang.org/api/oauth2/v1" (the auto-generated low-level APIs) instead of the high-level "golang.org/x/oauth2" package.

**Comment by SpaceNav** [comment]
My code can't seem to find that package?

Thanks for you help!
Dave

mailbox.go:21: can't find import: "golang.org/x/oauth2"



------ Original Message ------

**Comment by gmlewis** [comment]
`go get golang.org/x/oauth2`
